### ISSUE TITLE
UTF-8 with BOM encoding broken: syntax error at or near ""

### ISSUE THREAD

**Issue by Git-me-outta-here** [sqlc-dev/sqlc#1007]
All of my migrations files are UTF-8 except for one, which is UTF-8 with BOM.

That's where I get `syntax error at or near ""`... Could you allow sqlc to read this encoding?

**Comment by kyleconroy** [comment]
My plan is to create an internal `utfbom` package that has one function, DiscardBOM. It will take a byte slice and return a byte slice, which should work for all the cases we read in SQL files.

**Comment by bodison** [comment]
yeah would be fine as well. or a package that wraps the file reader?

As I mentioned in the closed PR, the test coverage of these four files would be a separate issue.
