### ISSUE TITLE
MySQL: Syntax error occured when I declared LIMIT with named parameter

### ISSUE THREAD

**Issue by 44smkn** [sqlc-dev/sqlc#1025]
#### What happened

[PlayGround](https://play.sqlc.dev/p/26cb5e0ba0f3fec43de2a32327aec7e9c40d6605e99c0f709d599f513af1a934)

I am trying to generate MySQL Query. but I got the error:  
`_sql/query/chair.sql:22:11: syntax error near "sqlc.arg(view_count);"`

```sql
CREATE TABLE chair (
    id          BIGINT  NOT NULL,
    name        TEXT    NOT NULL,
    kind        TEXT    NOT NULL,
    stock       INT     NOT NULL,
    PRIMARY KEY (id)
);

-- name: ListChairWithCondtion :many
SELECT * FROM chair
WHERE kind = sqlc.arg(kind)
ORDER BY stock DESC, id ASC
LIMIT sqlc.arg(view_count);
```

#### Environment

engine: mysql

```sh
$ uname
Darwin
$ uname -m
x86_64
$ sqlc version
v1.8.0
```

**Comment by Dugin123** [comment]
Me too.
Mysql named parameter not work.
And like statemen too.

**Comment by kyleconroy** [comment]
This is currently an issue with the upstream MySQL parser. It doesn't allow for function calls after LIMIT. The current workaround is to use regular positional parameters.

https://play.sqlc.dev/p/61fa8b0fe7fd1c24ebc7b03c5bea6d4386e8da6b14a7f63314dc91b823504c9e

**Comment by jamisonhyatt** [comment]
I went looking in https://github.com/pingcap/parser for the upstream issue and can't find anything regarding this - curious if you think it's worth creating one or not (not suggesting you take that on, just curious)
