### ISSUE TITLE
Feature request: add name of query to errors

### ISSUE THREAD

**Issue by carlmjohnson** [sqlc-dev/sqlc#1076]
So, if I have a query like

```sql
-- name: MyQuery :exec
UPDATE mytable SET col = $1 WHERE id = $2;
```

And it returns an error `pq: duplicate key value violates unique constraint "col"`, I would like it if it were prefixed with `query MyQuery: …`. This can be added after the fact with wrappers, but it's convenient for sqlc to add it for me.

**Comment by carlmjohnson** [comment]
FWIW, I made [a DBTX wrapper](https://github.com/spotlightpa/almanack/blob/ac460e310306732e1e709d924f48fd46d2588cdf/internal/db/logger.go) that uses runtime.Caller to figure out the function name and log it. You could use it to wrap errors too.

**Comment by kyleconroy** [comment]
I'd rather support this via some type of middleware so the behavior can be adjusted via code.
