### ISSUE TITLE
generate snakecase style variable in go from snakecase db field returning.

### ISSUE THREAD

**Issue by immysec** [sqlc-dev/sqlc#1127]
Input:

```sql
create table if not exists Servers(
    server_name varchar,
    cost_monthly numeric not null default 0
);

-- name: AddServer :one
insert into servers (
    server_name,
    cost_monthly
) values (
    $1, $2
) returning server_name;
```

Output:
```go
// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const addServer = `-- name: AddServer :one
insert into servers (
    server_name,
    cost_monthly
) values (
    $1, $2
) returning server_name
`

type AddServerParams struct {
	ServerName  sql.NullString
	CostMonthly string
}

func (q *Queries) AddServer(ctx context.Context, arg AddServerParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, addServer, arg.ServerName, arg.CostMonthly)
	var server_name sql.NullString
	err := row.Scan(&server_name)
	return server_name, err
}

```

Should the `server_name` variable in go code be `serverName` for go idioms? Or something config I missed? [sqlc playground example](https://play.sqlc.dev/p/7a2be74f5f9b97699a56a4321a184198d23341dec43e3c380b89ded192d6fe50).

**Comment by kyleconroy** [comment]
Since these variables are only referenced inside a function and never exposed, I think this is a low priority issue. That said, I believe that these variables might cause linter failures. If that's the case, we can change the format.

**Comment by immysec** [comment]
Yes, it causes linter failures in Goland IDE.

**Comment by digitive** [comment]
No, we should keep the first letter uppercase for public access, otherwise how could a caller outside db package construct arg varable?

**Comment by kyleconroy** [comment]
@digitive Please re-read the issue. This isn't about changing the the field name in the `Params` struct, it's about changing the case of an internal variable name that is never exposed to the caller.
