### ISSUE TITLE
Type overrides not honored for slices depending on whether the override is nullable

### ISSUE THREAD

**Issue by qualidafial** [sqlc-dev/sqlc#1158]
We had a problem in sqlc that had us scratching our heads for a while.

We have a type override that maps the `macaddr` PostgreSQL data type to Go type `null.String`:

```
{
  "go_type": "domain.com/path/to/package/null.String",
  "db_type": "macaddr",
  "nullable": true
},
```

This works great until we try to bind a mac address array. In this example we want to select multiple rows based on a unique `mac_address` column:

```
-- name: SelectDevices :many
SELECT
    *
FROM
    devices
WHERE
    mac_address = ANY(@mac_addresses::macaddr[])
```

However when we run `sqlc generate`, the `mac_addresses` parameter is generated as `[]net.HardwareAddress` instead of `[]null.String` as expected:

```
func (q *Queries) SelectDevices(ctx context.Context, macAddresses []net.HardwareAddr) ([]Device, error) {
    ...
}
```

The problem turned out to be the `"nullable": true` part of our override.

It appears that when you cast to types like `macaddr[]` in SQL, sqlc assumes that type is non-nullable.

Adding this override fixed our problem:

```
{
  "go_type": "string",
  "db_type": "macaddr",
  "nullable": false
},
```

And changed our generated code to:

```
func (q *Queries) SelectDevices(ctx context.Context, macAddresses []string) ([]Device, error) {
    ...
}
```

This problem kept us running in circles for the better part of a day. Would it be possible to update the documentation on the Configuration File page, and add a callout in the Type Overrides section that array parameters are assumed to be non-nullable?

**Comment by kyleconroy** [comment]
The behavior is seriously confusing, sorry for that. Tracking documentation improvements as a first step to improving the override experience.

https://github.com/sqlc-dev/sqlc/issues/2762
