### ISSUE TITLE
Comparison with sqlboiler

### ISSUE THREAD

**Issue by 4nte** [sqlc-dev/sqlc#1226]
As a user of https://github.com/volatiletech/sqlboiler, I'm curious about the key differences between the two projects.

I'm hoping we could assemble a list of key differences, pros/cons, preferably by developers who had experience with both libraries. As a relatively new user of sqlboiler, I'm not qualified to do so, So I'll gladly help with curating and double-checking along the way.

**Comment by echarrod** [comment]
I just read [Encore's summary of ORMs in 2024](https://encore.dev/resources/go-orms), it has pros + cons for both sqlc and sqlboiler on there 👍
