### ISSUE TITLE
"empty edit contents" with simple CTE

### ISSUE THREAD

**Issue by kevinburke** [sqlc-dev/sqlc#1313]
### Version

1.10.0

### What happened?

https://play.sqlc.dev/p/441110edfa4a433aa756df84248a3afbbb27f31ed1ef77c6dc0df6ff88a13208

I'm trying to build my way up to putting this query in sqlc: https://github.com/kevinburke/rickover/blob/master/models/queued_jobs/queued_jobs.go#L158-L204

But I tried to reduce it to the above query and got a funky answer. FWIW I can run that query in the psql console and it works just fine.

**Comment by kyleconroy** [comment]
This feels like a regression to me. Will look into it.

**Comment by kyleconroy** [comment]
A workaround is to give the columns [an alias](https://play.sqlc.dev/p/10146d47412afd09e5ad944f0ad851eefd97b745ba07679845a73c7ae92f206f).

```sql
-- name: TestRecursive :one
WITH t1 AS (
    select 1 as foo
)
SELECT * FROM t1;
```

**Comment by saward** [comment]
I'm getting the same error message, is this the same issue?

schema:
```
CREATE OR REPLACE FUNCTION public.fn_test_dynamic_now()
    RETURNS TABLE(when_time timestamptz) VOLATILE AS $BODY$
BEGIN
RETURN QUERY 
EXECUTE format('
  select now()
');
 END;
$BODY$ LANGUAGE 'plpgsql';
```

query `select * from fn_test_dynamic_now();` results in `query.sql:34:1: empty edit contents`.

or `select when_time from fn_test_dynamic_now();` results in `query.sql:34:8: column "when_time" does not exist`.

(line numbers being high are because I have more queries in there that work).

**Comment by kyleconroy** [comment]
Coming back to the original query in question, I don't think we can support it. When you execute the query in PostgreSQL, the column name that comes back is `?column?`. The workaround I originally posted is probably the correct thing to do.

```sql
# WITH t1 AS (
    select 1
)
SELECT * FROM t1;
 ?column? 
----------
        1
```
