### ISSUE TITLE
Add support for created_at/updated_at/deleted_at columns

### ISSUE THREAD

**Issue by teejae** [sqlc-dev/sqlc#1327]
### Version

1.11.0

### What happened?

Lots of ORMs automatically add handling for the row update tracking columns `created_at` etc.

It would be nice to have a way to either enforce or auto-generate the values of those columns without having to manually type them in all relevant queries.

Schema:
```sql
CREATE TABLE stuff (
    id bigserial PRIMARY KEY,
    name varchar(12),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);
```

Queries:
```sql
-- name: CreateStuff :one
INSERT INTO
    stuff (name)
VALUES
    ($1) RETURNING *;

-- name: UpdateStuff :exec
UPDATE
    stuff
SET
    name = $1;
```

Strawman proposals:

Proposal 1: Enforcement of inclusion of columns at compile time

```sql
-- compiler errors
-- name: CreateStuff :one
INSERT INTO
    stuff (name)
VALUES
    ($1) RETURNING *;

-- name: UpdateStuff :exec
UPDATE
    stuff
SET
    name = $1;

-- valid
INSERT INTO
    stuff (name, created_at)
VALUES
    ($1, $2) RETURNING *;

UPDATE
    stuff
SET
    name = $1,
    updated_at = $2;
```

Proposal 2: Autogen of columns
```sql
-- valid
INSERT INTO
    stuff (name)
VALUES
    ($1) RETURNING *;

UPDATE
    stuff
SET
    name = $1;

-- generated
INSERT INTO
    stuff (name, created_at)
VALUES
    ($1, $2) RETURNING *;

UPDATE
    stuff
SET
    name = $1,
    updated_at = $2;
```

### Database schema

```sql
CREATE TABLE stuff (
    id bigserial PRIMARY KEY,
    name varchar(12),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);
```

### Playground URL

https://play.sqlc.dev/p/ca838d66e9ad7a5592a5e41604a65468fbc46b440a06c94db638b84a4be4af83

**Comment by Jille** [comment]
created_at works automatically due to the `DEFAULT CURRENT_TIMESTAMP`, right?

What are you hoping will happen for deleted_at? Should sqlc add `WHERE deleted_at IS NULL` to all (sub)queries+joins?

Have you considered using a trigger to automatically update updated_at?

**Comment by teejae** [comment]
@Jille i'd like the ability for the app to actually put in both update/create timestamps, rather than having the database populate that information.

**Comment by aeq-dev** [comment]
+1 
Hope this will be done soon :)
