### ISSUE TITLE
INT64 not recognized

### ISSUE THREAD

**Issue by danthegoodman1** [sqlc-dev/sqlc#1394]
### Version

1.11.0

### What happened?

A column of `tokens INT8 NOT NULL`  is recognized as an `int64` in go, but `tokens INT64 NOT NULL` is an `interface{}`

### Database schema

```sql
CREATE TABLE test (
  tokens INT64 NOT NULL,
  PRIMARY KEY (tokens)
);
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Is this a CockroachDB extension? int64 is not a valid PostgreSQL type

```
$ psql
psql (14.1)
Type "help" for help.

kyle=# CREATE TABLE foobar (num INT64);
ERROR:  type "int64" does not exist
LINE 1: CREATE TABLE foobar (num INT64);
```

**Comment by danthegoodman1** [comment]
@kyleconroy i apologize, I was under the impression is was in Postgres! I’ll know better to check next time first now :)

**Comment by ajwerner** [comment]
FWIW, cockroach might accept `INT64` but it's just an alias internally for `INT8`. Honestly, it's confusing. Seems fine to never implement support for `INT64`.
