### ISSUE TITLE
Error generating code when using parameters whose inferred names are go keywords

### ISSUE THREAD

**Issue by natasha-jarus** [sqlc-dev/sqlc#1412]
### Version

1.10.0

### What happened?

If you create a query with a single positional parameter whose inferred arg name is a go keyword (e.g., `WHERE type = $1`), sqlc reports a generation error:
```
error generating code: source error: 21:54: expected 'IDENT', found 'type'
```
Adding a second query parameter allows the code generation to succeed. Currently the workaround is to use an explicitly named parameter (e.g., `WHERE type = @my_type`).

### SQL queries

```sql
-- error generating code:
SELECT *
FROM my_table
WHERE type = $1;

-- this works fine:
SELECT *
FROM my_table
WHERE type = $1 AND TRUE = $2;

-- this is also ok:
SELECT *
FROM my_table
WHERE type = @my_type;
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by mohammadVatandoost** [comment]
I like to work on this bug, please assign me.
My Solution: In this if, we check Params.Column.name to see if it is a golang specific keywords or not. If it is, we should capitalize it.
`
if len(query.Params) == 1 {
			p := query.Params[0]
			gq.Arg = QueryValue{
				Name:       paramName(p),
				Typ:        goType(r, p.Column, settings),
				SQLPackage: sqlpkg,
			}
		}
`

Golang Specific Keywords are defined [here](https://golang.org/ref/spec#Keywords).

**Comment by ddway2** [comment]
Hi do you have already a fix for this problem ?

**Comment by mohammadVatandoost** [comment]
Hi, I checked the code base, My suggestion was applied to the code. It should be fixed now. I don't know why issue still is open.
