### ISSUE TITLE
sqlite: parentheses in filter change generated functions

### ISSUE THREAD

**Issue by espang** [sqlc-dev/sqlc#1828]
### Version

1.15.0

### What happened?

I wanted to add following query:

```
-- name: NextTask :one
SELECT id
FROM dt_tasks
WHERE
    (execute_at IS NULL
    OR execute_at <= ?)
    AND task_status = 'scheduled'
LIMIT 1;
```

but  the function it generates doesn't contain the parameter:
```
func (q *Queries) NextTask(ctx context.Context) (int64, error)
```
and using it returns an error: "not enough args to execute query: want 1 got 0".

When I remove the parentheses in the filter the generated function takes the additional parameter. I could make it work when I change the query to:

```
-- name: NextTask :one
SELECT id
FROM tasks
WHERE
    execute_at IS NULL
    AND task_status = 'scheduled'
    OR execute_at <= ?
    AND task_status = 'scheduled'
LIMIT 1;
```

The generated function has following signature:
```
func (q *Queries) NextTask(ctx context.Context, executeAt sql.NullString) (int64, error)
```

### What operating system are you using?

macOS

### What type of code are you generating?

Go

**Comment by handysuherman** [comment]
any update for this issue?, seems like not solved yet till now.

**Comment by orisano** [comment]
The latest version seems to have fixed this issue.
https://play.sqlc.dev/p/692327e703c842e9f899af1c9dbff8b83276dedc36a9d3e3777079691d1f303e
