### ISSUE TITLE
Error generating code for mysql table with "-" in the table name

### ISSUE THREAD

**Issue by zhengyangfeng00** [sqlc-dev/sqlc#1845]
### Version

1.15.0

### What happened?

Running sqlc to generate go code results in an error: `error generating code: source error: 22:9: expected type, found '-' (and 10 more errors)`

I believe the reason is that the table name contains "-" and sqlc tries to generate the struct with "-" in it, which is an illegal golang struct name.

Example ddl:

```
CREATE TABLE IF NOT EXISTS `x-info` (
  `date` DATE NULL DEFAULT NULL,
  `meta` VARCHAR(50) NULL DEFAULT NULL,
  `count` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
```

### Relevant log output

```shell
error generating code: source error: 22:9: expected type, found '-' (and 10 more errors)
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS `x-info` (
  `date` DATE NULL DEFAULT NULL,
  `meta` VARCHAR(50) NULL DEFAULT NULL,
  `count` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
```

### SQL queries

```sql
-- name: Query :many
SELECT * FROM `x-info`
WHERE meta = ?
;
```

### Configuration

```yaml
- path: "go/gen/sqlc/xmetricssqlc"
    name: "xmetricssqlc"
    engine: "mysql"
    schema: "ddl.sql"
    queries: "queries.sql"
```

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Fixed https://play.sqlc.dev/p/5132c3b4c00aba7da20a15017b520853f97688ebe2a0da10b7ed388209c41a1f
