### ISSUE TITLE
Error when generating semantically correct `postgres` SQL

### ISSUE THREAD

**Issue by patrickdevivo** [sqlc-dev/sqlc#1858]
### Version

1.15.0

### What happened?

Hi! First of all thank you for all the hard work going into `sqlc` - we're big fans! We use `sqlc` for [this project](https://github.com/mergestat/fuse) and encountered an error when trying to compile a query that has 3 "parts" in a column name in a select:

```
unknown number of fields: 3
```

I've made this small repo to show reproduction of the issue: https://github.com/mergestat/sqlc-compile-bug

The error seems to originate here: https://github.com/kyleconroy/sqlc/blob/0a1b04eb47c80236db176805fe43f709042b805c/internal/compiler/output_columns.go#L474 where it looks like only 1 or 2 "parts" are permitted, when it should be possible to allow 3 (in our queries at least, which run fine in postgres directly).

We've been able to get around this by aliasing the `schema.table` in our query, so we only need to refer to a column with 2 "parts" - but it would still be nice to avoid this limitation (as it would allow us to keep our queries a bit cleaner, especially in more complex ones).

### Relevant log output

```shell
unknown number of fields: 3
```

### Database schema

```sql
CREATE SCHEMA some_schema;

CREATE TABLE some_schema.some_table (
  id   BIGSERIAL PRIMARY KEY,
  some_column  text
);
```

### SQL queries

```sql
-- AllRowsOK :many
SELECT id, some_table.some_column FROM some_schema.some_table;

-- AllRowsBug :many
SELECT id, some_schema.some_table.some_column FROM some_schema.some_table;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "example"
        out: "example"
```

### What operating system are you using?

Linux, macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by GeertJohan** [comment]
I encounter the same error for a slightly different scenario. In our schema.sql the following statement is present:
```
CREATE MATERIALIZED VIEW stock.available_quantities
AS 
SELECT
   stock.items.id AS item_id,
   items.available_quantity
FROM
   stock.items;
```

It fails on `stock.items.id`. The fix was easy ofcourse (just use `items.id`) but I thought it would be useful to report here :)
