### ISSUE TITLE
SQLite parser doesn't support JSONB columns

### ISSUE THREAD

**Issue by ammmir** [sqlc-dev/sqlc#1863]
### What do you want to change?

Schema:

```sql
CREATE TABLE IF NOT EXISTS users (
  id TEXT NOT NULL PRIMARY KEY,
  created_at INTEGER DEFAULT CURRENT_TIMESTAMP,
  config JSONB NOT NULL DEFAULT '{}'
);
```

Error: `unknown SQLite type: jsonb`

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
SQLite does not support JSONB. From their [docs](https://www.sqlite.org/json1.html):

> SQLite does not (currently) support a binary encoding of JSON. Experiments have been unable to find a binary encoding that is smaller or faster than a plain text encoding. (The present implementation parses JSON text at over 250 MB/s.) All JSON functions currently throw an error if any of their arguments are BLOBs because BLOBs are reserved for a future enhancement in which BLOBs will store the binary encoding for JSON.
