### ISSUE TITLE
Unable to Type Alias

### ISSUE THREAD

**Issue by christoph-pflueger** [sqlc-dev/sqlc#1866]
### Version

1.15.0

### What happened?

Example Query:

```sql
-- name: CheckIfSomeRandomColumnIsNotNull :one
SELECT
  `some_random_column` IS NOT NULL AS `is_some_random_column_not_null`
FROM
  `example`
WHERE
  `id` = ?;
```

Results in:

```go
type CheckIfSomeRandomColumnIsNotNullRow struct {
	IsSomeRandomColumnNotNull interface{}
}
```

Every attempt to use `::bool` to type the struct field correctly resulted in a syntax error.

### Database schema

```sql
CREATE TABLE `example` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `some_random_column` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Fixed https://play.sqlc.dev/p/49ae28cb5dac3a2020f72fc17203a53921e9882990987c1a23329b8125c16729
