### ISSUE TITLE
Support `EXISTS` in SQLite

### ISSUE THREAD

**Issue by marcusirgens** [sqlc-dev/sqlc#1925]
### What do you want to change?

`EXISTS` currently maps to `interface{}`. See example here: https://play.sqlc.dev/p/24898cbb74186ef12300101ab0b15249430ccce13fbe62c8e1657364a10b9db2

`query.sql`:
```sql
CREATE TABLE foos
(
    id    INTEGER PRIMARY KEY,
    color TEXT NOT NULL
);

-- name: HasColoredFoo :one
SELECT EXISTS(SELECT 1 FROM foos WHERE color = ?);
```

`sqlc.json`
```json
{
  "version": "2",
  "sql": [
    {
      "schema": "query.sql",
      "engine": "sqlite",
      "queries": "query.sql",
      "gen": {
        "go": {
          "package": "sqlc",
          "out": "."
        }
      }
    }
  ]
}
```

### What database engines need to be changed?

SQLite

### What programming language backends need to be changed?

Go

**Comment by marcusirgens** [comment]
This is possibly a duplicate of #1821.

**Comment by orisano** [comment]
The latest version seems to have fixed this issue.
https://play.sqlc.dev/p/c5253d7dad88853d64fee5ba76da673f6bf80378d9aeff110a19f1dee449835c
