### ISSUE TITLE
Being able to mark generated files with go:build tags

### ISSUE THREAD

**Issue by eladitzhakian** [sqlc-dev/sqlc#2012]
### What do you want to change?

It could be useful to be able to emit `// go:build some-tag` into the golang generated files

This way I can, for example, exclude them when running coverage tests 😇 

### What programming language backends need to be changed?

Go

**Comment by andrewmbenton** [comment]
This seems like a pretty easy option to add to the [sqlc v2 gen/go config](https://docs.sqlc.dev/en/latest/reference/config.html#go), if someone wants to take a crack at it.

**Comment by Hyuga-Tsukui** [comment]
I find this feature very useful, and I'd like to try contributing. Would that be okay?

**Comment by Hyuga-Tsukui** [comment]
@kyleconroy 

I find this feature very useful, and I'd like to try contributing. Would that be okay?
