### ISSUE TITLE
Improve package path detection

### ISSUE THREAD

**Issue by bokunodev** [sqlc-dev/sqlc#2123]
### What do you want to change?

https://github.com/kyleconroy/sqlc/blob/1832ce137a6c225c0d25e626ab6acfe3b5b61278/internal/config/go_type.go#L77

current package name detection could be improved.
package path that end with semver should be aliased as well, otherwise it may generate wrong package name.

```go
package db

import (
	"github.com/aofei/sandid"
	"github.com/gofrs/uuid/v5"
)

type TokenStore struct {
	AccessToken string
	AuthToken   v5.UUID // should be uuid.UUID
	ID          int32
	Expiry      int64
}
```

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
The `go_type` configuration option supports specifying individual parts of the import path for packages that have versions greater than `v1` https://docs.sqlc.dev/en/stable/reference/config.html#type-overriding
