### ISSUE TITLE
Couldn't find option to disable upppercase ID for every _id field

### ISSUE THREAD

**Issue by priyanshujain** [sqlc-dev/sqlc#2161]
I can see that `sqlc` create `ID` for every `_id` field suffix. Is there any parameter so that it generated capitalized `Id` instead of uppercase `ID` suffix.

For ex. currently it does
```
app_id      -> AppID
```

I want to do 
```
app_id      -> AppId
```

@kyleconroy Please help here.

**Comment by priyanshujain** [comment]
As I can see [here](https://github.com/kyleconroy/sqlc/blob/75ee59c83acc92a35bcb014ef01d4977dbe81bea/internal/codegen/golang/struct.go#L24), There is intentional modification of `id` to `ID`. Can you please help me understand the reason behind it? Thanks!

**Comment by sergey-tb** [comment]
@priyanshujain , it is because of this silly [naming convention rule](https://github.com/golang/go/wiki/CodeReviewComments#initialisms) in Go.

In reality people rarely follow it, due to KpmgWsUrl is easier to read than KPMGWSURL. However, sqlc also doesn't follow all acronyms, except for some reasons for ID. And unfortunately I'm not sure there is an option to turn it off.

**Comment by priyanshujain** [comment]
@sergey-tb Thanks. If I use renaming settings conf then it's a never-ending amount of work. 

Is it worth building a feature skipping initialisms for sqlc? As It says in go wiki
```
The code generated by the protocol buffer compiler is exempt from this rule. Human-written code is held to a higher standard than machine-written code.

```

And as go devs say - There's a never-ending list, we'll get it wrong, and it's simpler to stick with the current mechanical translation. ([link](https://github.com/golang/protobuf/issues/156#issuecomment-201006174))

Please let me know your thoughts. cc: @kyleconroy

**Comment by sergey-tb** [comment]
@priyanshujain , I'm not a contributor of sqlc, but for sure agree initialism should be configured. I like how some linters do it, eg: initialism : ["id","url"]
