### ISSUE TITLE
[proposal] Support LOAD DATA LOCAL INFILE for MySQL

### ISSUE THREAD

**Issue by Jille** [sqlc-dev/sqlc#2179]
https://github.com/go-sql-driver/mysql#load-data-local-infile-support supports LOAD DATA LOCAL INFILE with an io.Reader.

We could implement the :copyfrom query annotation to use LOAD DATA LOCAL INFILE when using go-sql-driver. The generated code would call https://pkg.go.dev/github.com/go-sql-driver/mysql#RegisterReaderHandler with a new reader for this call (and deregister it afterwards).

I propose to keep the same :copyfrom name and semantics, even though that's technically incorrect for MySQL.

I've looked at the three MySQL drivers listed on https://github.com/golang/go/wiki/SQLDrivers and the other two don't seem to support LOAD DATA [LOCAL] INFILE, though they might support it in the future.

We'd probably want to add a setting where people can indicate which MySQL driver they're using so we can generate the code using the relevant package.

**Comment by Jille** [comment]
Some more thoughts:

* We need to encode the sqlc rows to TSV (or another CSV-like format) that is accepted by LOAD DATA INFILE. I propose to create an external library for that and let the generated code depend on it. (It felt like too much to generate inline.)

* We need to configure sqlc which mysql driver is used, because database/sql doesn't natively support LOAD DATA INFILE. I think `sql_package` is the right place to put that. Passing `go-sql-driver/mysql` would behave mostly the same as passing `database/sql`, except that it allows `:copyfrom` support

**Comment by Jille** [comment]
I have two PRs ready for this, and a documentation branch I'll send later.

https://github.com/kyleconroy/sqlc/pull/2220
https://github.com/kyleconroy/sqlc/pull/2219
https://github.com/Jille/sqlc/compare/loaddata2...loaddata3

**Comment by Jille** [comment]
I need go-sql-driver/mysql to expose the *time.Location to encode correctly.

@SnoozeThis https://github.com/go-sql-driver/mysql/issues/1416 || https://github.com/go-sql-driver/mysql/pull/1419

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/NFrLngXswx4) I will either wait until https://github.com/go-sql-driver/mysql/issues/1416 is closed or until https://github.com/go-sql-driver/mysql/pull/1419 is merged and then add a comment.

**Comment by SnoozeThis** [comment]
An error occurred while snoozing: not found
