### ISSUE TITLE
sqlc.arg and @ does not work when queries getting complicated  

### ISSUE THREAD

**Issue by Shihansin** [sqlc-dev/sqlc#2202]
### Version

1.17.2

### What happened?

```-- name: CreatePercentPromo :one
WITH new_promo AS (
  INSERT INTO promotion (name, description, start_date, end_date)
  VALUES ($1, $2, $3, $4)
  RETURNING id
), new_promo_configs AS (
  INSERT INTO promotion_config (product_id, promotion_id, pd_start_date, pd_end_date)
  SELECT unnest(@product_id::BIGINT[]), (SELECT id FROM new_promo), $6, $7
)
RETURNING * ;

this doesn't  work , it return 

db/queries/createpromo.sql:1:1: could not determine data type of parameter $5
make: *** [Makefile:17: sqlc] Error 1

```

```-- name: CreatePercentPromo :one
WITH new_promo AS (
  INSERT INTO promotion (name, description, start_date, end_date)
  VALUES ($1, $2, $3, $4)
  RETURNING id
), new_promo_configs AS (
  INSERT INTO promotion_config (product_id, promotion_id, pd_start_date, pd_end_date)
  SELECT unnest($5::BIGINT[]), (SELECT id FROM new_promo), $6, $7
)
RETURNING * ;

this works, but return column5
 ```
 
 
if you have a more complicated query like above , then @ and sqlc,arg does not work 

### Relevant log output

```shell
db/queries/createpromo.sql:1:1: could not determine data type of parameter $5
make: *** [Makefile:17: sqlc] Error 1
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by rmt-javier** [comment]
or don't skip the `$5` in the first case

```
WITH new_promo AS (
  INSERT INTO promotion (name, description, start_date, end_date)
  VALUES ($1, $2, $3, $4)
  RETURNING id
), new_promo_configs AS (
  INSERT INTO promotion_config (product_id, promotion_id, pd_start_date, pd_end_date)
  SELECT unnest(@product_id::BIGINT[]), (SELECT id FROM new_promo), $5, $6
)
RETURNING * ;
```

**Comment by Shihansin** [comment]
> or don't skip the `$5` in the first case
> 
> ```
> WITH new_promo AS (
>   INSERT INTO promotion (name, description, start_date, end_date)
>   VALUES ($1, $2, $3, $4)
>   RETURNING id
> ), new_promo_configs AS (
>   INSERT INTO promotion_config (product_id, promotion_id, pd_start_date, pd_end_date)
>   SELECT unnest(@product_id::BIGINT[]), (SELECT id FROM new_promo), $5, $6
> )
> RETURNING * ;
> ```


It doesn't work  , I think because sqlc couldn't calculate the queue order ，when the query gets complicated.

**Comment by kyleconroy** [comment]
This bug report doesn't have enough information for us to reproduce. Could you please reproduce it on https://play.sqlc.dev and share a link here?
