### ISSUE TITLE
Plugin examples should not use imports from internal 

### ISSUE THREAD

**Issue by corpix** [sqlc-dev/sqlc#2251]
### Version

1.17.2

### What happened?

[This page](https://docs.sqlc.dev/en/latest/guides/plugins.html#process-plugins) says:
> Process-based plugins offer minimal security. Only use plugins that you trust. Better yet, only use **plugins that you’ve written yourself**.

I do want to write a plugin myself. Following first link from the docs and see this https://github.com/kyleconroy/sqlc/blob/main/cmd/sqlc-gen-json/main.go
![image](https://user-images.githubusercontent.com/747362/235700722-a9f4a258-3dad-4245-a4b8-737e0eb8fdca.png)

Of course it fails with:

```
package command-line-arguments
        main.go:10:2: use of internal package github.com/kyleconroy/sqlc/internal/codegen/json not allowed
...
```

Should I copy-paste the data-structures (like `plugin.CodeGenRequest`) from the sqlc codebase? This looks wrong.

**Comment by kyleconroy** [comment]
For WASM-plugins, I'd suggest looking at these two repos (https://github.com/tabbed/sqlc-gen-kotlin and https://github.com/tabbed/sqlc-gen-python) as they do not depend on any internal code. The plugin authoring documentation is sparse right now. It's on our list to make it better soon.

For a full set of working plugins, see https://docs.sqlc.dev/en/latest/reference/language-support.html.
