### ISSUE TITLE
Data type not correct when using AS and double quotes

### ISSUE THREAD

**Issue by philon123** [sqlc-dev/sqlc#2255]
### Version

1.17.2

### What happened?

Generated struct for the SELECT:

```go
type GetAPIsRow struct {
	Account   string
	Token     interface{}
	ReadToken string
}
```

Both `token` and `read_token` should be `string`. But token gets `interface{}`. Removing the quotes around `token` yields the correct result. 

### Database schema

```sql
CREATE TABLE api (
  id   BIGSERIAL PRIMARY KEY,
  username text      NOT NULL,
  api_config  json
);
```

### SQL queries

```sql
-- name: GetAPIs :one
SELECT 	p.username AS account,
	p.api_config ->> 'api_key'::text AS "token",
	p.api_config ->> 'read_token'::text AS read_token
FROM api p;
```

### Playground URL

https://play.sqlc.dev/p/e36f821259124f4056ceaae5b0425738c3aebdccbc7038e9774354587ec92971

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by orisano** [comment]
Maybe the below query is correct.
```sql
-- name: GetAPIs :one
SELECT 	p.username AS account,
	(p.api_config ->> 'api_key')::text AS "token",
	(p.api_config ->> 'read_token')::text AS read_token
FROM api p;
```
This works correctly.

https://play.sqlc.dev/p/0696e78d053f44ca049ef2f9f08d46eb69275ac7b0b5704caf90a8823298acff

**Comment by philon123** [comment]
oh, missing brackets.. I should have caught that one. Still strange that one of the values got string assigned anyway, while interface{} should habe been assigned to both values? But maybe I just mistyped that in the issue description. Thanks for spending time on this, I will close the issue.
