### ISSUE TITLE
Unknown node type *ast.SetOprStmt

### ISSUE THREAD

**Issue by dansimau** [sqlc-dev/sqlc#2260]
### Version

1.17.2

### What happened?

sqlc fails to generate on MySQL when there is a UNION inside a subquery that we're selecting from.

### Relevant log output

```shell
sqlc generate failed.
2023/05/04 09:31:21 dolphin.convert: Unknown node type *ast.SetOprStmt
2023/05/04 09:31:21 dolphin.convert: Unknown node type *ast.SetOprStmt
# package db
query.sql:9:1: edited query syntax is invalid: syntax error near "FROM ("
```

### SQL queries

```sql
-- name: TestSubqueryUnion :many
SELECT tmp.* FROM (
  SELECT * FROM authors
  UNION
  SELECT * FROM authors
) tmp LIMIT 5;
```

### Playground URL

https://play.sqlc.dev/p/4963c8a8ba696143e0a564fa4c164c51c54d9460b5494c32ddc2c0269a20f866

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Fixed in https://github.com/sqlc-dev/sqlc/pull/2843. Will be released in v1.23 in a few weeks
