### ISSUE TITLE
CASE WHEN does not work in SELECT field

### ISSUE THREAD

**Issue by dansimau** [sqlc-dev/sqlc#2261]
### Version

1.17.2

### What happened?

sqlc generate fails in MySQL if there is a CASE statement as a SELECT field.

### Relevant log output

```shell
sqlc generate failed.
# package db
query.sql:9:1: parse table name: unexpected node type: *ast.Integer
```

### Database schema

```sql
CREATE TABLE users (
  id   int PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: UserExists :one
SELECT
    CASE WHEN
        EXISTS (
            SELECT * FROM users WHERE id = '123'
        )
    THEN 1
    ELSE 0
END AS result;
```

### Playground URL

https://play.sqlc.dev/p/5aeef78626b3adaf91194dfd05854ca22d717e15114c01f8bb21d98826a39848

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by Sub6Resources** [comment]
Seeing the same issue with PostgreSQL engine

**Comment by Sub6Resources** [comment]
Looks like https://github.com/kyleconroy/sqlc/pull/2238 may have fixed this issue. I don't have time to build from source and see, but hopefully should be included in the next release.

**Comment by gnuletik** [comment]
@Sub6Resources you're right!

I gave a try to `go run github.com/kyleconroy/sqlc/cmd/sqlc@main generate -f ./sqlc.yaml` with Postgres.
And the issue was properly fixed with the proper generated types.

**Comment by kyleconroy** [comment]
Fixed! https://play.sqlc.dev/p/b8dad882c40da78fdce5449adff8abeba66f920a82882b8f647260b246b77e2c
