### ISSUE TITLE
sqlite engine cannot parse explicit null/unsigned in columns

### ISSUE THREAD

**Issue by danderson** [sqlc-dev/sqlc#2278]
### Version

Other

### What happened?

With sqlc 1.18.0.

I'm importing a schema from a Django app, by running `sqlite3` and dumping `.schema` into a file. This schema definition is exhaustive, and notably explicitly states whether each field is nullable or not, and whether integer fields are unsigned or not (the default if not specified is nullable and unsigned).

It seems like the sqlc parser doesn't understand explicit NULL or UNSIGNED in column definitions, and ends up interpreting something like `bool NULL` as a type named `boolnull`, and then of course fails because that type isn't known.

**This schema doesn't seem to error on the sqlc playground**, however the model it generates uses `interface{}` for all the nullable types, instead of `sql.Null*` types like it does with implicit null columns.

### Relevant log output

```shell
> sqlc generate
2023/05/14 10:53:29 unknown SQLite type: textnull
2023/05/14 10:53:29 unknown SQLite type: smallintunsigned
2023/05/14 10:53:29 unknown SQLite type: integernull
2023/05/14 10:53:29 unknown SQLite type: boolnull
2023/05/14 10:53:29 unknown SQLite type: datetimenull
2023/05/14 10:53:29 unknown SQLite type: datenull
2023/05/14 10:53:29 unknown SQLite type: textnull
2023/05/14 10:53:29 unknown SQLite type: smallintunsigned
2023/05/14 10:53:29 unknown SQLite type: integernull
2023/05/14 10:53:29 unknown SQLite type: boolnull
2023/05/14 10:53:29 unknown SQLite type: datetimenull
2023/05/14 10:53:29 unknown SQLite type: datenull
```

### Database schema

```sql
CREATE TABLE repro (
       id integer not null primary key autoincrement,
       txt text null,
       i smallint unsigned,
       inull integer null,
       b bool null,
       dt datetime null,
       d date null);
```

### SQL queries

```sql
-- name: GetRepro :one
select * from repro where id = ? limit 1;
```

### Configuration

```yaml
version: 2
sql:
  - engine: sqlite
    schema: schema.sql
    queries: query.sql
    gen:
      go:
        package: db
        out: db
```

### Playground URL

https://play.sqlc.dev/p/fa5a5b563ccdd910ee61f97bc1781462f42bf49e0811768778f8b99d41c292a9

### What operating system are you using?

Linux

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment]
In my brief testing this appears to be an issue with the underlying sqlite parser: https://github.com/antlr/antlr4

In particular, the type `Column_defContext` returns the incorrectly-merged type names (e.g. "textnull") when calling `def.Type_name().GetText()`.

There may be a hacky workaround available by inspecting the column constraints and, if they are correct, doing some string splitting, but it's probably best to approach the maintainer of the parsing library about a patch. I'm not sure I'm up to that task, but I suppose I can try if nobody else has time or inclination.

**Comment by andrewmbenton** [comment]
Following up on my last comment, I didn't realize that the sqlite parser is *generated* using antlr, and so sqlc actually is the "maintainer". We should take a look at the parser generator inputs and figure out the right way to proceed.

**Comment by danderson** [comment]
I'm theoretically willing to try and figure it out, though I don't know antlr parsing at all and sqlc internals obviously even less. It's not super high urgency given that an obvious workaround exists.

**Comment by hakobera** [comment]
Current SQLite parser is based on official document.

https://www.sqlite.org/datatype3.html
https://www.sqlite.org/syntax/column-constraint.html

**Comment by ciarand** [comment]
Related to this, I'm running into issues with columns that define a default. I would expect this to work:

```sql
-- Example queries for sqlc
CREATE TABLE Names (
  name TEXT NOT NULL DEFAULT ""
) WITHOUT ROWID;

-- name: QueryNames :many
SELECT * FROM Names;
```

But the cli tool (v1.19.1) is failing with the error:

>unknown SQLite type: textnotnulldefault

**Comment by ciarand** [comment]
Awesome, thanks!

**Comment by erlangparasu** [comment]
> ### Version
> 
> Other
> ### What happened?
> 
> With sqlc 1.18.0.
> 
> I'm importing a schema from a Django app, by running `sqlite3` and dumping `.schema` into a file. This schema definition is exhaustive, and notably explicitly states whether each field is nullable or not, and whether integer fields are unsigned or not (the default if not specified is nullable and unsigned).
> 
> It seems like the sqlc parser doesn't understand explicit NULL or UNSIGNED in column definitions, and ends up interpreting something like `bool NULL` as a type named `boolnull`, and then of course fails because that type isn't known.
> 
> **This schema doesn't seem to error on the sqlc playground**, however the model it generates uses `interface{}` for all the nullable types, instead of `sql.Null*` types like it does with implicit null columns.
> ### Relevant log output
> 
> > sqlc generate
> 2023/05/14 10:53:29 unknown SQLite type: textnull
> 2023/05/14 10:53:29 unknown SQLite type: smallintunsigned
> 2023/05/14 10:53:29 unknown SQLite type: integernull
> 2023/05/14 10:53:29 unknown SQLite type: boolnull
> 2023/05/14 10:53:29 unknown SQLite type: datetimenull
> 2023/05/14 10:53:29 unknown SQLite type: datenull
> 2023/05/14 10:53:29 unknown SQLite type: textnull
> 2023/05/14 10:53:29 unknown SQLite type: smallintunsigned
> 2023/05/14 10:53:29 unknown SQLite type: integernull
> 2023/05/14 10:53:29 unknown SQLite type: boolnull
> 2023/05/14 10:53:29 unknown SQLite type: datetimenull
> 2023/05/14 10:53:29 unknown SQLite type: datenull
> 
> ### Database schema
> 
> CREATE TABLE repro (
>        id integer not null primary key autoincrement,
>        txt text null,
>        i smallint unsigned,
>        inull integer null,
>        b bool null,
>        dt datetime null,
>        d date null);
> 
> ### SQL queries
> 
> -- name: GetRepro :one
> select * from repro where id = ? limit 1;
> 
> ### Configuration
> 
> version: 2
> sql:
>   - engine: sqlite
>     schema: schema.sql
>     queries: query.sql
>     gen:
>       go:
>         package: db
>         out: db
> 
> ### Playground URL
> 
> https://play.sqlc.dev/p/fa5a5b563ccdd910ee61f97bc1781462f42bf49e0811768778f8b99d41c292a9
> ### What operating system are you using?
> 
> Linux
> ### What database engines are you using?
> 
> _No response_
> ### What type of code are you generating?
> 
> Go

Got same issue
