### ISSUE TITLE
Add support for POSTGIS geometry type 

### ISSUE THREAD

**Issue by rupertevill** [sqlc-dev/sqlc#231]
The following SQL:

```sql
CREATE TABLE test_table (
    geometry_column GEOMETRY
);
```

yields the following error when using 'sqlc generate':

```
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
2020/01/07 11:33:35 unknown Postgres type: geometry
```

It would be fantastic if geometry could default to simply use the sql.NullString for now. 

If it is added, it allows me to reference the geometry type from https://github.com/paulmach/go.geojson as the type override (at the package level). Rather than having to reference each geometry column separately if I want to override the type.

**Comment by clansofts** [comment]
@rupertevill, I have fixed this particular error by doing the following.
in your sqlc.json add following override

"overrides": [
    {
      "go_type": "github.com/twpayne/go-geom.MultiPolygon",
      "db_type": "geography",
      "null": true
    },
    {
      "go_type": "github.com/twpayne/go-geom.MultiPolygon",
      "db_type": "geometry",
      "null": true
    }]

In my case am using both geometry and geography . with default of MultiPolygons

Its generating below field

type Boundary struct {
	ID             int64             `json:"id"`
	Uid            uuid.UUID         `json:"uid"`
	BlockNo        sql.NullString    `json:"block_no"`
	ParcelNo       sql.NullString    `json:"parcel_no"`
	Geom           geom.MultiPolygon `json:"geom"`
}

**Comment by tschaub** [comment]
I'm curious how others are dealing with the need to call `ST_AsBinary` or `ST_AsEWKB` when selecting or `ST_GeomFromEWKB` etc on insert.  I've reported the trouble I've been having in #384.

**Comment by egtann** [comment]
For completeness, here's how I was able to insert using `postgis.PointS` on a `geometry(Point, 4326)` column:

```
-- name: CreateGeo :exec
INSERT INTO geo_data (location) VALUES (ST_GeomFromEWKB(@location));
```

Then using it:

```
err := db.CreateGeo(ctx, postgis.PointS{
    SRID: 4326,
    X: 1,
    Y: 2,
})
```
