### ISSUE TITLE
support for parsing custom SQL type

### ISSUE THREAD

**Issue by dangquangdon** [sqlc-dev/sqlc#2340]
### What do you want to change?

At the moment, for complex queries that include `JOIN` statements and the parsed function returns `interface{}` object that basically can be anything. I think it would be nice if we support parsing `CREATE TYPE` statements if provided and use it as the return type of those complex queries  🤔 

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
Duplicate of #2760
