### ISSUE TITLE
Insert statement should support WITH clause

### ISSUE THREAD

**Issue by odannyc** [sqlc-dev/sqlc#2350]
### What do you want to change?

The query:

```sql
INSERT INTO some_table
WITH foo AS (
...
)
SELECT ...
FROM another_table
JOIN foo ON ...
WHERE ...
```

The error:
```
relation "foo" does not exist
```

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
As of 1.21 this has been fixed 

https://play.sqlc.dev/p/227535df10665296e2e11e50393290fdce360825e98d6255d8f7af6c613ca7b7
