### ISSUE TITLE
Parameters with Array type have incorrect names

### ISSUE THREAD

**Issue by ErrorBoi** [sqlc-dev/sqlc#243]
### What happened?

Hello, I'm trying to generate Go Code from SQL Query using ANY method. When I run `sqlc generate`, variable with array method gets unexpected name.

**Actual result:** Variable with []int type gets `dollar_1` name
**Expected result:** Variable gets `IDs` name

**Note:** variable might get `Column + Number` name (e.g. Column4) when sql query contains several ANY methods in it. 

### Database schema

```sql
CREATE TABLE pilots (
  id BIGSERIAL PRIMARY KEY
);
```

### SQL queries

```sql
-- name: ListPilotsByIDs :many
SELECT * FROM pilots
WHERE id = ANY($1::int[]);
```

### Playground URL

https://play.sqlc.dev/p/455e276514a8ecf33f4d86175da22a6965058d86d08a9e127c59e3a3a9acbad4

**Comment by kyleconroy** [comment]
Agreed that this is a bug. In the meantime, you can use named parameters to get the correct parameter name:

```sql
-- name: ListPilotsByIDs :many
SELECT * FROM pilots
WHERE id = ANY(sqlc.arg(ids)::int[]);
```

Or using the `@` shortcut:


```sql
-- name: ListPilotsByIDs :many
SELECT * FROM pilots
WHERE id = ANY(@ids::int[]);
```

**Comment by MinSomai** [comment]
This works.
```sql
-- name: ListTransfers :many
SELECT * FROM transfers
WHERE
    from_account_id = ANY(sqlc.arg(from_account_ids)::int[]) OR
    to_account_id = ANY(sqlc.arg(from_account_ids)::int[]);
```
Below doesn't. any solution to this?
```sql
-- name: ListTransfers :many
SELECT * FROM transfers
WHERE
    from_account_id = ANY(sqlc.arg(from_account_ids)::int[]) OR
    to_account_id = ANY(sqlc.arg(from_account_ids)::int[])
ORDER BY id
LIMIT $1
OFFSET $2;
```
error
```
query mixes positional parameters ($1) and named parameters (sqlc.arg or @arg)
```

**Comment by theenoahmason** [comment]
@kyleconroy How can I accomplish the above example in MySQL?

```
-- name: ListPilotsByIDs :many
SELECT * FROM pilots
WHERE id = ANY(@ids::int[]);
```

`sqlc.arg('ids')::int[]` results in a syntax error.

**Comment by Xeoncross** [comment]
Looks like sqlc needs to support passing slices to MySQL queries #695 first

**Comment by kyleconroy** [comment]
This can be accomplished in MySQL and SQLite using sqlc.slice.

As for the parameter name, sqlc.arg Anand named parameters solve this issue nicely.
