### ISSUE TITLE
Option to remove sqlc version from generated files

### ISSUE THREAD

**Issue by PatrLind** [sqlc-dev/sqlc#2450]
### What do you want to change?

I would like an option to remove the sqlc version from the generated files.

Every time I update sqlc all generated files change, but normally the only change is the sqlc version at the top of the file. To me it is not important to know what sqlc version generated the files, so I would like to have an option to remove it.

**Comment by kyleconroy** [comment]
Thanks for opening the issue. While the file changes can be annoying when upgrading versions, it's helpful to know what version generated that code. If you'd like to remove it, I'd suggest using a post-processor step.
