### ISSUE TITLE
Include getters and setters with models so we may  work with interfaces instead of specific structs

### ISSUE THREAD

**Issue by blwsh** [sqlc-dev/sqlc#2466]
### What do you want to change?

Selecting all fields and a subset of fields for the same table yields different structs.  Currently, we're required to write a mapper function which transforms the row(s) in to an abstraction our applications can understand - however, if sqlc was to provide getters and setters, we'd be able to define interfaces which the results conform to and leave a lot of the heavy lifting to go.

Please see the example below:

```sql
CREATE TABLE `products`
(
    `name`  varchar(255) NOT NULL,
    `price` int(11)      NOT NULL
)
```

```go
// generated models/queries

// select * from products
type Product struct {
  Name string
  Price int
}
func (p Product) GetName() string { ... }
func (p Product) GetPrice() int { ... }

// select `name` from products
type ProductNameRow struct {
  Name string
}
func (p ProductNameRow) GetName() string { ... }

// app

type ProductWithName interface {
  GetName() string
}

func DoesProductHaveCoolName[T ProductWithName](product T) bool { ... }

DoesProductHaveCoolName(&ProductNameRow{}) // good
DoesProductHaveCoolName(&Product{}) // also good
```

For this particular problem extending the template for structs to include getters and setters would be sufficient, however - it may be a better idea to allow the extension of the template via the config file instead?

### What database engines need to be changed?

PostgreSQL, MySQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
Closed via https://github.com/sqlc-dev/sqlc/pull/2471#issuecomment-1656307541
