### ISSUE TITLE
`sqlc` generated code as `repository` pattern of clean architecture

### ISSUE THREAD

**Issue by Larleyt** [sqlc-dev/sqlc#2467]
As the title states, I'm wondering if it is possible to use `sqlc` generated code as `repository` pattern of clean architecture paradigm?
Are there any examples of such implementation?

Thanks,

**Comment by Jille** [comment]
Could you elaborate more on what the repository pattern is? What exactly do you want?

**Comment by Jille** [comment]
Is this a duplicate of #2469?

**Comment by kyleconroy** [comment]
Duplicate of https://github.com/sqlc-dev/sqlc/issues/2469
