### ISSUE TITLE
Implement support for `CAST(expr AS type-name)` with SQLite engine

### ISSUE THREAD

**Issue by andrewmbenton** [sqlc-dev/sqlc#2541]
### What do you want to change?

sqlc understands casting for postgresql and soon mysql. We should add it for sqlite as well.

Currently things are pretty broken: https://play.sqlc.dev/p/e653d75ac564b18a73b0c459ade58b2b4653aee02f3058481471212a93bad890

### What database engines need to be changed?

SQLite

**Comment by orisano** [comment]
This is already fixed by #2470

**Comment by robertkozin** [comment]
Thank you @orisano! I was running into this. ❤️ 

To any readers, I installed the latest commit with `go install github.com/sqlc-dev/sqlc/cmd/sqlc@main`

**Comment by andrewmbenton** [comment]
@orisano Oh yeah I missed that, thanks!
