### ISSUE TITLE
array column added from alter table are generated as non array

### ISSUE THREAD

**Issue by Andy-William** [sqlc-dev/sqlc#2571]
### Version

1.20.0

### What happened?

On alter tables, array columns are generated as non array. This doesn't happen in 1.19.

![image](https://github.com/sqlc-dev/sqlc/assets/6039182/9793ab4a-f432-481f-b099-018bacd68d1f)

### Database schema

```
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  array1 BIGINT[],
  array2 BIGINT array
);

ALTER TABLE authors ADD COLUMN array3 BIGINT[];
ALTER TABLE authors ADD COLUMN array4 BIGINT array;
```

### SQL queries

```
-- name: GetAuthor :one
SELECT * FROM (select id from authors) t;
```

### Configuration

```
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

 https://play.sqlc.dev/p/09d13d4e8c68bda99da95e6e0af5adf85c60396277614faae148fd8b56a9dec4

**Comment by pmorelli92** [comment]
I am experiencing the same.
