### ISSUE TITLE
postgres arrays now generated as scalars in models

### ISSUE THREAD

**Issue by josharian** [sqlc-dev/sqlc#2605]
### Version

1.20.0

### What happened?

In v1.19.x, our model looked like:

```go
type Bonus struct {
	ID              uuid.UUID
        // snip
	Employees       []int32
}
``` 

Generated with v.1.20.0, it is now:

```go
type Bonus struct {
	ID              uuid.UUID
        // snip
	Employees       int32
}
``` 

The slice for Employees has been lost.

Bisected to 3c9ef73dd379613ff682326a58d402f0695f3242 (cc @colli173)

```sql
# \d bonus;
                                               Table "public.bonus"
      Column       |              Type              | Collation | Nullable |               Default                
-------------------+--------------------------------+-----------+----------+--------------------------------------
 id                | uuid                           |           | not null | gen_random_uuid()
-- snip
 employees         | integer[]                      |           | not null | '{}'::integer[]
```

This blocks us from upgrading to v1.20.

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by orisano** [comment]
@josharian Is it a column added with ALTER TABLE?
If so, #2572 may have solved the problem. (not yet released)

Can you reproduce it in playground (play.sqlc.dev)?

**Comment by josharian** [comment]
Yeah, appears to be fixed at main. Thanks, 🤞🏽 for a release soon.
