### ISSUE TITLE
Missing Docker images for supported platforms

### ISSUE THREAD

**Issue by michaelzx** [sqlc-dev/sqlc#2609]
### What do you want to change?

sqlc/sqlc, Some versions only have amd64, and some versions only have arm64.
kjconroy/sqlc,  both arm64 and amd64 are in every version.

**Comment by kyleconroy** [comment]
Our release workflow builds a multiarch image, I'm not sure exactly what's gone wrong.

**Comment by kyleconroy** [comment]
Not exactly sure what the issue was, but I've re-run the build and things look to be fixed for 1.20.0 

https://hub.docker.com/layers/sqlc/sqlc/1.20.0/images/sha256-a2357bef31931fb6331938416163c651dd978558efbaa395bffc077f1e1fba64?context=repo

**Comment by zcubbs** [comment]
thank you
