### ISSUE TITLE
Add support for `CALL` statements in MySQL

### ISSUE THREAD

**Issue by andrewmbenton** [sqlc-dev/sqlc#2612]
### What do you want to change?

Calling stored procedures is currently impossible with the MySQL engine. Here's a playground link:

https://play.sqlc.dev/p/f89f9de548fed5f1a23e3372932d252e0d3d525b8a4556ea008519dc32bb8879

Original Discord thread: https://discord.com/channels/946447283321438248/1139700396395352147

### What database engines need to be changed?

MySQL

**Comment by orisano** [comment]
SQLite does not have a call statement

**Comment by andrewmbenton** [comment]
> SQLite does not have a call statement

Thanks, I should have checked. I've updated the issue title and description.

**Comment by orisano** [comment]
related issue: https://github.com/sqlc-dev/sqlc/issues/1403
