### ISSUE TITLE
Version 2 config, error generating code: source error: 5:15: expected ';', found '.' 

### ISSUE THREAD

**Issue by Nikola-Milovic** [sqlc-dev/sqlc#2628]
### Version

1.20.0

### What happened?

Playing around with SQLC I decided to create a small demo app, but to my surprise it seems that the v2 config is not working as expected and I couldn't find anything in the docs to steer me into correct setup. If this isn't an issue, please do improve the docs to mention what I am I doing wrong since I was following them

### Playground URL

https://play.sqlc.dev/p/42be5fcd145656dd7706ca696ff301a4e58f6136f22277529ecd1d29cbd59cf8

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by orisano** [comment]
The package property should be "db" and not "github.com/Nikola-Milovic/slq-gen/db".
https://play.sqlc.dev/p/48121b9ab4607c8bac94410eeb1f7651a4642b828610d14e933150ab58436a3a
