### ISSUE TITLE
varchar[] is generated as string instead of []string

### ISSUE THREAD

**Issue by InbarPerry** [sqlc-dev/sqlc#2638]
### Version

1.20.0

### What happened?

SQLC is generating base type (not array) for columns that was added in a separate migration.
This is a new bug introduced in 1.20 (worked in 1.19)

### Relevant log output

```shell
// Output in sqlc 1.19:

type Author struct {
	ID    uuid.NullUUID
	Books []string
}

// Output in sqlc 1.20:

type Author struct {
	ID    uuid.NullUUID
	Books string
}
```

### Database schema

```sql
CREATE TABLE authors (
  id UUID
);

ALTER TABLE authors ADD COLUMN IF NOT EXISTS books VARCHAR(255)[] DEFAULT NULL;
```

### Playground URL

(1.20) https://play.sqlc.dev/p/53e5f0dcb79fb2071328bfdb8507b08b340bfc6024735b53b27a89260d147647
(1.19) https://play.sqlc.dev/p/5f0472ede5543014774f5115321cb73d09e336c8230b90d464892c185a75972e

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by orisano** [comment]
@InbarPerry This problem has already been solved by https://github.com/sqlc-dev/sqlc/pull/2572 (not yet released)

**Comment by Ikeh-Akinyemi** [comment]
Just ran into the same issue. When is the release scheduled for? I'm sort of stagnant as a result of it.

**Comment by IkehAkinyemi** [comment]
Just ran into the same issue. When is the release scheduled for? I'm sort of stagnant as a result of it.

**Comment by InbarPerry** [comment]
Closed issue because it's duplicate of https://github.com/sqlc-dev/sqlc/issues/2571
