### ISSUE TITLE
Subquery support?

### ISSUE THREAD

**Issue by MicahKimel** [sqlc-dev/sqlc#2642]
### Version

1.20.0

### What happened?

Is there subquery support in sqlc for mysql? I wrote 

```
Select item from (select t.item as item from table as t) as a
where a > 0;
```

but sqlc is not able to use my alias, how can I fix this.

Thank you!!

### Relevant log output

```shell
table alias "a" does not exist
make: *** [sqlc] Error 1
```

### SQL queries

```sql
Select item from (select t.item from table as t) as a
where a > 0;
```

**Comment by andrei-dascalu** [comment]
Hm, I think general subquery support exists as for the most part SQL is taken as-is. I've used stuff like `WHERE Id NOT IN (Select WhateverKey FROM differentTable)` however I've never tried to select results from a subquery into the main one. 

I've done a playground test like so https://play.sqlc.dev/p/489502d547de5890c422020c84fa41a1b92bb7c280565bb517f1f28af2556408 which seems to resolve.

**Comment by kyleconroy** [comment]
Yes, sqlc supports subqueries for MySQL. You may run into some cases where they don't work. If that's the case, please open a issue with a complete example of the query that doesn't work, including the database schema.
