### ISSUE TITLE
Automatically generate unit tests

### ISSUE THREAD

**Issue by dandee** [sqlc-dev/sqlc#2652]
### What do you want to change?

It would be great to automate creation of unit tests for the generated functions. So for each xxx.go generated file there would be accompanying xxx_test.go.

### What database engines need to be changed?

None

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
This is a great example of a feature request that could work as a codegen plugin. Different folks might have very different ideas on the types of tests to write.

**Comment by dandee** [comment]
Hey! It's a good suggestion! I'm a fresh user of the project so I haven't thought about this approach.
