### ISSUE TITLE
sqlc does not recognize the sqlc.yaml file

### ISSUE THREAD

**Issue by chaehyun29** [sqlc-dev/sqlc#2675]
### Version

1.20.0

### What happened?

hello

I tried sqlc generate using the sqlc/sqlc:latest Docker image in a Windows env, 
but I only got an error saying the file does not exist.

Below is my work environment and error details.

OS : Windows 11 Home
Docker : Docker Desktop 4.22.0
Go : go1.20.6

tried commands :
```
docker run --rm -v ${PWD}:/src -w /src sqlc/sqlc generate
docker run --rm -v ${PWD}:/src -w /src kjconroy/sqlc generate 
```
(I tried both!)

The contents of the folder pointed to by ${PWD) are as follows.

```
-- queries
   └- query.sql
-- main.exe
-- go.sum
-- main.go
-- schema.sql
-- go.mod
-- sqlc.yaml
```

I tried running it all in Gitbash, cmd and Powershell in administrator mode.
What could be the problem?

### Relevant log output

```shell
error parsing configuration files. sqlc.yaml or sqlc.json: file does not exist
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment]
I don't think this is an issue with sqlc, so will close for now.

I'm not a docker expert but this seems like a volume mount problem. Are you sure that `${PWD}` is interpreted by docker the way you expect it to? For instance, if you `echo $PWD` inside your shell what do you get? Do you need to use `${pwd}` or `${$PWD}` instead? Maybe you can use an explicit path to your host directory to see if that works?
