### ISSUE TITLE
sqlc generates invalid code for inserts returning * when `query_parameter_limit` > 2

### ISSUE THREAD

**Issue by andrewmbenton** [sqlc-dev/sqlc#2678]
### Version

1.20.0

### What happened?

The insert query function is missing a variable to scan into when `query_parameter_limit` > 2. It appears that the number of query parameters must also be > 2 but <= `query_parameter_limit` to trigger the invalid codegen.

See the playground link for an example.

### Playground URL

https://play.sqlc.dev/p/e986c5254a2e3c9d6c62daa78950d545417c92622f97b7d0ee59433baa727cd5

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by orisano** [comment]
Seems to be working fine (HEAD).

my local:
```go
func (q *Queries) CreateAuthor(ctx context.Context, iD int64, name string, bio sql.NullString) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, iD, name, bio)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
```

**Comment by kyleconroy** [comment]
I think there was a PR that recently fixed this. I merged it yesterday or Monday.

**Comment by orisano** [comment]
https://github.com/sqlc-dev/sqlc/pull/2578
