### ISSUE TITLE
int instead of []int if add column through alter table

### ISSUE THREAD

**Issue by Spargwy** [sqlc-dev/sqlc#2688]
### Version

1.20.0

### What happened?

Check playground please

Here you can see that generated model has FirstArray and SecondArray fields but second is just int. It was added with alter table

### Playground URL

https://play.sqlc.dev/p/305666ed7e83bf64a45853b49beb5fe88fbf4c6e70f093e3225fea82a503dad3

**Comment by orisano** [comment]
This problem has already been solved by https://github.com/sqlc-dev/sqlc/pull/2572 (not yet released)
