### ISSUE TITLE
Add support for sqlc JSON schema in Schema Store

### ISSUE THREAD

**Issue by remyleone** [sqlc-dev/sqlc#2693]
### What do you want to change?

I would like to have support in https://www.schemastore.org/json/ for the sqlc format https://docs.sqlc.dev/en/stable/reference/config.html

This would be helpful to have native support in editor for writing sqlc configuration files.

**Comment by orisano** [comment]
I wrote a json schema
https://gist.github.com/orisano/99925f79abd463b6c73687710de580d4

**Comment by remyleone** [comment]
Thanks a lot, I'm going to submit it to the schema store and will keep you updated here.

**Comment by remyleone** [comment]
https://github.com/SchemaStore/schemastore/pull/3191

**Comment by kyleconroy** [comment]
These are now committed to the repo and tested

https://github.com/sqlc-dev/sqlc/blob/main/internal/config/v_one.json
https://github.com/sqlc-dev/sqlc/blob/main/internal/config/v_two.json
