### ISSUE TITLE
`sql.NullString` is used when field is filtered with `is not null`

### ISSUE THREAD

**Issue by jamietanna** [sqlc-dev/sqlc#2723]
### Version

1.21.0

### What happened?

I'm unsure if this is a bug or maybe a feature request.

When crafting a query, filtering with a `WHERE <field> IS NOT NULL`, I'd (_maybe_ ?) expect this to be returning `string` not an `sql.NullString`.

I've used v1.20.0 in the playground as v1.21.0 is returning an HTTP 500 error.

### Playground URL

https://play.sqlc.dev/p/616d691ebd54faab288c774e1b41a588cc2d4328ebe9b84b880dbecb72fa1223

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go

**Comment by orisano** [comment]
This is a feature request

**Comment by kyleconroy** [comment]
Thanks for the feature request! This proposal reminds me of [narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) from TypeScript. Sadly, this isn't something we can easily support right now in sqlc, as our type inference is primitive. We'd need to add a significant amount of code to ensure that the inference worked for many different types of expressions.
