### ISSUE TITLE
Error while downloading sqlc with tag nowasm 

### ISSUE THREAD

**Issue by reva-gupta** [sqlc-dev/sqlc#2724]
### Version

1.21.0

### What happened?

I ran `go install -tags=nowasm github.com/kyleconroy/sqlc/cmd/sqlc@latest` to grab the latest version of sqlc and ran into an error. 
During the last version bump the [struct in nowasm](https://github.com/sqlc-dev/sqlc/blob/main/internal/ext/wasm/nowasm.go#L12) was not updated with the new field.  

### Relevant log output

```shell
# github.com/sqlc-dev/sqlc/internal/cmd
../../go/pkg/mod/github.com/sqlc-dev/sqlc@v1.21.0/internal/cmd/generate.go:395:5: unknown field Env in struct literal of type wasm.Runner
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
`go install -tags=nowasm github.com/kyleconroy/sqlc/cmd/sqlc@main` should now work. Let me know if it's still broken.
