### ISSUE TITLE
Add the ability to modify queries before making the actual request

### ISSUE THREAD

**Issue by kibblerz** [sqlc-dev/sqlc#2728]
### What do you want to change?

So there's been some talk about allowing dynamically generated queries, though it seems that this capability has been dismissed. 

An example is when filtering through a table with a multitude of filters. Currently, you need to set up a separate query for each column that's being filtered. This can get messy and convoluted. I understand that dynamic query support can be considered bad practice. So I was thinking of a different possible solution.

I think it'd be helpful to create a function/method that will allow modifying a query before the request is made. So then, for multiple filters, one could get the query string from sqlc before making the request, and for example do a loop to append things like where filters. I expect this should be simple enough.

### What database engines need to be changed?

PostgreSQL, MySQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
The generated code today does not have a hook for manipulating the query body before it is sent to the database. This feature would require a large change to the generated methods, which isn't something we're looking to do right now. We're continuing to look for better ways to support dynamic queries in a way that prevents SQL injection and provides for static, known queries at runtime.

**Comment by kcmvp** [comment]
This feature is really nice & powerful! Hope to see it soon!
