### ISSUE TITLE
Allow `sqlc.arg` to work when inside a `case` statement

### ISSUE THREAD

**Issue by jamietanna** [sqlc-dev/sqlc#2736]
### What do you want to change?

Probably a feature not a bug, as it's not supported as far back as 1.18.0 on the playground.

Maybe also wild that this is something that may be relied upon  😅

For example [in this playground link](https://play.sqlc.dev/p/fd81a234e14567a2721f57f4818114d0f3af763f082a53112fdba293ce6c5d7c) I'd expect to see an argument provided for `name`, but it's not present.

### What database engines need to be changed?

SQLite

### What programming language backends need to be changed?

Go

**Comment by jamietanna** [comment]
A workaround is shown at https://play.sqlc.dev/p/17100a7824bde725cc8c4984f5c9c08923fd2dc698bc281b391d309132c11924 where you need to have referenced the parameter already in the query

**Comment by orisano** [comment]
Two problems are causing this issue
* sqlite engine does not support "when ~ case ~ then ~"
* The compiler infers any as the type of a parameter that it only compares to a constant
