### ISSUE TITLE
support custom generation template

### ISSUE THREAD

**Issue by yuzhouu** [sqlc-dev/sqlc#2741]
### What do you want to change?

For my case, I need to custom enum to support marshalJSON and unmarshalJSON. (yaml, toml and etc.)

Relying solely on configuration options is insufficient to meet the diverse range of real-world needs. Supporting custom templates allows for maximum flexibility to meet user requirements.

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
Our current Go templates are not in a state to be exposed as a public interface. For now, the best option would be to create another plugin that allows for customer user templates that could be generated side-by-side with code from sqlc.
