### ISSUE TITLE
Support emitting accessor methods to enable Go interfaces?

### ISSUE THREAD

**Issue by evankanderson** [sqlc-dev/sqlc#2746]
### What do you want to change?

It would sometimes be handy to be able to handle multiple database rows with common field names using some Go code which implements generic operations (for example, checking that a user token contains a group claim that matches the `group_id` of some database object).

It would be handy in these cases if the objects all implemented a `GetGroupID()` method, which could be used to match the types to an interface.  For example:

```golang

type List struct {
  ID int64 `json:"id"`
  GroupID int64 `json:"group_id"`
}

func (l List) GetID() int64 {
  return l.ID
}

func (l List) GetGroupID() int64 {
  return l.GroupID
}
```

And then elsewhere (which would define the `database.GroupIDer` interface):

```golang
func IsAuthorized(claims []int64, obj database.GroupIDer) bool {
  return slices.Contains(claims, obj.GetGroupID())
}
```

### What database engines need to be changed?

None

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
@evankanderson This isn't something we're planning on adding to sqlc, as we think it's better served by using a separate tool to generate these interfaces from structs. See my comment here https://github.com/sqlc-dev/sqlc/pull/2471#issuecomment-1656307541
