### ISSUE TITLE
COALESCE creates an interface{} type instead of the actual go type.

### ISSUE THREAD

**Issue by vamshiaruru** [sqlc-dev/sqlc#2752]
### Version

1.21.0

### What happened?

For a query like this
```
-- name: ProductDefaultReviewStats :one
SELECT COUNT(*) AS total_count,
    COALESCE(SUM(rating.score), 0) AS total_score
FROM rating
WHERE rating.product_id = @product_id;
```

The struct generated is
```go
type ProductDefaultReviewStatsRow struct {
	TotalCount int64       `db:"total_count" json:"total_count"`
	TotalScore interface{} `db:"total_score" json:"total_score"`
}
```

How do I make sqlc generate a particular type here? I tried doing  ` COALESCE(SUM(rating.score), 0::int)` as well, and that doesn't help.  

### Database schema

```sql
CREATE TABLE rating (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    score INTEGER NOT NULL,
    product_id INTEGER REFERENCES product(id),
);
```
```


### SQL queries

```sql
-- name: ProductDefaultReviewStats :one
SELECT COUNT(*) AS total_count,
    COALESCE(SUM(rating.score), 0) AS total_score
FROM rating
WHERE rating.product_id = @product_id;
```
```


### Configuration

_No response_

### Playground URL

_No response_

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment]
So `sqlc` generally has a tough time with type inference in these situations. I was able to coerce using a cast outside the `COALESCE` function call though (i.e. use `COALESCE(SUM(rating.score), 0)::int `). See this playground link for a working example: https://play.sqlc.dev/p/a87c7456d4fdeaf5c5509218b952c0fc9e2f664dcc0553e51251df1440e53b4c

**Comment by vamshiaruru** [comment]
Thank you @andrewmbenton , that works for me :)
