### ISSUE TITLE
sqlc generate failed with mysql's geometry field type .

### ISSUE THREAD

**Issue by bagualing** [sqlc-dev/sqlc#2767]
### What do you want to change?

Hi, My table have a geometry(Point) type. I got a syntax error when I run the "sqlc generate" command:

`schema.sql:4:17: syntax error near "point DEFAULT NULL COMMENT 'location',"`

Here is the content of **schema.sql** file:
```
CREATE TABLE hotel (
  id int NOT NULL AUTO_INCREMENT COMMENT 'Id',
  name varchar(50) NOT NULL COMMENT 'hotel name',
  location point DEFAULT NULL COMMENT 'location',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
COMMENT = 'hotel info';
```
The "location" is a point type field. **I don't know how to write the "Type overriding" configuration for this point type?**
 
  
And, Here is the content of **query.sql** file:
```
-- name: NewHotel :exec
INSERT INTO hotel (name, location) VALUES(?, POINT(?, ?));

-- name: UpdateHotelLocation :exec
UPDATE hotel SET location = POINT(?,?) WHERE id = ?;

-- name: GetNearbyHotels :many
SELECT h.id, h.name, ST_X(h.location) AS longitude, ST_Y(h.location) AS latitude, 
  ROUND(ST_DISTANCE_SPHERE(POINT(sqlc.arg(x),sqlc.arg(y)), h.location)) AS distance 
FROM hotel h
WHERE ST_DISTANCE_SPHERE(POINT(sqlc.arg(x),sqlc.arg(y)), h.location) <= sqlc.arg(radius);
```

Since the previous step didn't work, I'm not sure if these SQL statements can be generated properly by sqlc?
In particular, in the **GetNearbyHotels** query statement, how can sqlc sense that the **radius** parameter in the Where clause should be treated as a floating point type?

P.S
_"POINT" and "ST_DISTANCE_SPHERE" are mysql‘s geometry funcations.
The ST_DISTANCE_SPHERE function is used to calculate the distance between two locations on Earth._

### What database engines need to be changed?

MySQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
pingcap/parser doesn't support spatial datatypes https://github.com/pingcap/parser/issues/853

Until the parser is fixed to support those types, you won't be able to use sqlc.

https://play.sqlc.dev/p/244eb39fb3c366ca047a1409d182b882e46de9d6ae80853d86bbbf9a025c9dae

**Comment by bagualing** [comment]
@kyleconroy Thank you, Kyle.
So, the second question: How can I make sqlc generate correctly data type for the function's return value which in the select or where clauses? 
For example, the price field of the hotel table is numeric type, but after a function call, it returns a string type: 
`select mysql_or_user-defined_func1(price), ... from hotel where mysql_or_user-defined_func1(price)=?`

**Comment by kyleconroy** [comment]
The solution right now is to use an explicit `CAST`, which I know isn't a great solution. We're working on a better solution, but it's still in the works.

**Comment by bagualing** [comment]
> The solution right now is to use an explicit `CAST`, which I know isn't a great solution. We're working on a better solution, but it's still in the works.

I used the `CAST` function, but it still couldn't generate the correct field type.
