### ISSUE TITLE
pgx/v5 and "strings"

### ISSUE THREAD

**Issue by polderudo** [sqlc-dev/sqlc#2771]
### Version

1.21.0

### What happened?

Generated queries with sql_package: "pgx/v5" and "select * where param in (sqlc.slice(names));" will add "strings" to the query, although it is not used.

Work correct if "any(sqlc.arg" is used with postgres

### Playground URL

https://play.sqlc.dev/p/591af7d9f7f7aa988af96e7cf21876ae140669067b2b6baccc2b28e48f91ab87

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
PostgreSQL has native support for arrays, so you don't need to use `sqlc.slice`. Instead, you can use ANY with a cast to an array of text.

https://play.sqlc.dev/p/b36cb5dc10bf3f8b2e449a7d3bb20efa6ee0349d641f15811248826edb0cc511

**Comment by polderudo** [comment]
> PostgreSQL has native support for arrays, so you don't need to use `sqlc.slice`. Instead, you can use ANY with a cast to an array of text.
> 
> https://play.sqlc.dev/p/b36cb5dc10bf3f8b2e449a7d3bb20efa6ee0349d641f15811248826edb0cc511

Yes i know, thats why i wrote that "any" is working correct. But though you might be interested, maybe some sort of race condition, that "strings" is imported at all. 
Thanks for looking over it. And thanks for the lib. Your work is awesome!
