### ISSUE TITLE
docs: HTML `id` attributes in the changelog should be stable to enable linking

### ISSUE THREAD

**Issue by andrewmbenton** [sqlc-dev/sqlc#2783]
### What do you want to change?

See https://docs.sqlc.dev/en/stable/reference/changelog.html and note the permalink anchors for section headings. Many are generated with fragments like `#id1`, `#id2` etc which shift as new content is added to the top of the document.

**Comment by kyleconroy** [comment]
Fixed by https://github.com/sqlc-dev/sqlc/pull/2784
