### ISSUE TITLE
Can sqlc put comment after struct's field?

### ISSUE THREAD

**Issue by bagualing** [sqlc-dev/sqlc#2785]
### What do you want to change?

sqlc generates code in the following style:

```
// Hotel Info
type Hotel struct {
	// Hotel ID
	ID int64 `db:"id"`
	// Hotel Name
	HotelName string `db:"hotel_name"`
}
```

Can sqlc put comment after struct's field like this style:
```
// Hotel Info
type Hotel struct {
	ID int64 `db:"id"`                    // Hotel ID
	HotelName string `db:"hotel_name"`    // Hotel Name
}
```

### What database engines need to be changed?

MySQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
Either syntax is valid according to https://tip.golang.org/doc/comment. The reason we put the comments aboves the fields is that we don't know how long each comment is going to be.
