### ISSUE TITLE
unsupported reference type: <nil>

### ISSUE THREAD

**Issue by nithish-suresh** [sqlc-dev/sqlc#2787]
### Version

1.22.0

### What happened?

Can't we pass the where condition as a paramter?
**I want to pass the entire query as a parameter.**

When performing sqlc generate on the below query
SELECT * FROM <table_name> WHERE $1; 

it throws,
unsupported reference type: <nil>

**Comment by orisano** [comment]
This is not a bug.
Even in normal SQL, it is not possible to parameterize the conditional statement itself.

**Comment by 1AbdulKareem** [comment]
@orisano Saying that where clauses can't be parametrized is bullshit !

Almost every software in the industry parametrize where clauses somehow .

Even SQLC can parametrize it , try the following example : 

```
-- name: SelectAddon :many
	SELECT id, name, version, categ, premium, hr_cost 
	FROM "addon"
	WHERE ? $1 
	ORDER BY ? $2
	LIMIT $3
	OFFSET $4
``` 

but you will have to sanitize it somehow to be more safer

**Comment by 1AbdulKareem** [comment]
In fact this is a bug .  The where clause's  mission is to filter out data .  how on earth where clause can't be parametrized ! even pure simple pl/plsql functions can do it `select * from parametrizedSelect(table,domain,orderby,limit,offset) ; ` , and return the wanted rows . I advice you to educate yourself more about databases and a bit more about SQL .
