### ISSUE TITLE
Inserting N records in one query

### ISSUE THREAD

**Issue by GetPsyched** [sqlc-dev/sqlc#2792]
### What do you want to change?

I have a REST API writting in Go and I use SQLC for all the querying. However, I've felt very limited by the fact that I cannot have a function that bulk inserts to the database.

There are 2 workarounds for this:
1. Call the single insert function N times.
2. Use a raw function for a custom query (potentially unsafe)

I apologise if this feature already exists; I looked through the docs and several other places but couldn't find anything that hinted towards this feature.

### What database engines need to be changed?

PostgreSQL, MySQL, SQLite

### What programming language backends need to be changed?

Go, Python, Kotlin

**Comment by orisano** [comment]
https://docs.sqlc.dev/en/latest/howto/insert.html#using-copyfrom

**Comment by GetPsyched** [comment]
Yeah, I've discovered that and experimenting with it. Sadly it errors out for non-parameter values:
```
database/queries/club/member.sql:1:1: :copyfrom doesn't support non-parameter values
```

**Comment by orisano** [comment]
If it doesn't work, a reproduced link on play.sqlc.dev would be helpful.
What database engine are you using?

**Comment by orisano** [comment]
Currently, copyfrom with subquery is not supported

**Comment by GetPsyched** [comment]
Cool, no problem. Thanks for the help!
