### ISSUE TITLE
Add a generated header to the schema-file

### ISSUE THREAD

**Issue by kevinawoo** [sqlc-dev/sqlc#2809]
### What do you want to change?

When generating the `schema.sql` file (in my case, Postgres), is it possible to add a header to the file indicating it's been generated?

eample:
```sql
-- Code generated by sqlc. DO NOT EDIT.
-- versions:
--    sqlc v1.20.0
```

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
I'm not sure I understand this request. sqlc will generate `db.go`, `models.go` and a `<filename>.sql.go` for each query. All three of those files are generated with the header you've mentioned. sqlc doesn't generate schema.sql files automatically.

**Comment by kevinawoo** [comment]
OH! I'm so sorry, I mixed up the the file generated from https://github.com/amacneil/dbmate. Closing this issue.
