### ISSUE TITLE
support multiple SQL files

### ISSUE THREAD

**Issue by Goldziher** [sqlc-dev/sqlc#2816]
### What do you want to change?

Hi!

I would like to ask for support for multiple SQL files.

e.g. support 

```yaml
queries: './sql/query.sql'
```

But also
```yaml
queries: ['./sql/x.sql', './sql/y.sql']
```

Optionally glob patterns can also be supported.

Why? My queries file is becoming pretty large and hard to navigate. It would be much easier to handle as a bunch of files.

**Comment by Goldziher** [comment]
Lol, well i just tried it and its supported.

```yaml
      queries:
        - './sql/queries/application.sql'
        - './sql/queries/project.sql'
        - './sql/queries/prompt-config.sql'
        - './sql/queries/prompt-request-record.sql'
        - './sql/queries/token.sql'
        - './sql/queries/user-account.sql'
        - './sql/queries/user-project.sql'
```

I suggest updating the documentation.

**Comment by ahmafi** [comment]
It doesn't support glob patterns though, right?
