### ISSUE TITLE
Cannot generate sqlite delete exec with slice named arg using `sql.slice`

### ISSUE THREAD

**Issue by vietvudanh** [sqlc-dev/sqlc#2874]
### Version

1.22.0

### What happened?

As in the title, I cannot generate sqlite delete exec with slice named arg using `sql.slice`.

If I use no name arg then it genrated just fine:

```sql
-- name: DeleteStories :exec
DELETE from stories where url in (sql.slice(?));
```
generated: 
```
const deleteStories = `-- name: DeleteStories :exec
DELETE from stories where url in (sql.slice(?))
`

func (q *Queries) DeleteStories(ctx context.Context, slice interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteStories, slice)
	return err
}
```

### Relevant log output

```shell
const deleteStories = `-- name: DeleteStories :exec
DELETE from stories where url in (sql.slice(ids))
`

func (q *Queries) DeleteStories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStories)
	return err
}
```

### Database schema

```sql
CREATE TABLE stories (
    id      INTEGER PRIMARY KEY,
    title   TEXT NOT NULL,
    url     TEXT NOT NULL,
    author  TEXT NOT NULL,
    created_at DATETIME DEFAULT (DATETIME('now')),
    updated_at DATETIME DEFAULT (DATETIME('now'))
);
```

### SQL queries

```sql
-- name: DeleteStories :exec
DELETE from stories where url in (sql.slice(ids));
```

### Configuration

```yaml
version: 2
sql:
  - engine: "sqlite"
    schema: "schema.sql"
    queries: "query.sql"
```

### What operating system are you using?

macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go

**Comment by juanjuanzero** [comment]
Hello there, i tried to replicate your issue using what you have provided in the [playground](https://play.sqlc.dev/p/be3c989369a13ee69908c69a061a25f245568b02cc9ee5cc4fdef574339a720e).

I'm getting the output, is there something I could be missing?
```
const deleteStories = `-- name: DeleteStories :exec
DELETE from stories where url in (sql.slice(ids))
`
```

**Comment by orisano** [comment]
repro: https://play.sqlc.dev/p/0a8af4a1ba05c1ae505a7dda4da2d9cb9ebb8f1bfb5f30fad3df8a6038463bdc

**Comment by orisano** [comment]
https://play.sqlc.dev/p/b8dda6caa984d3bb8dd05cf52da9ae85038ab5766ba70acd2750ae53fbe2fe25
You mistyped sqlc.slice as sql.slice.
It is not a bug.

**Comment by vietvudanh** [comment]
> https://play.sqlc.dev/p/b8dda6caa984d3bb8dd05cf52da9ae85038ab5766ba70acd2750ae53fbe2fe25 You mistyped sqlc.slice as sql.slice. It is not a bug.

Oh my bad, didn't see the problem. I will close this issue. Thank you very much.
