### ISSUE TITLE
Get a row of joined tables as a struct with inner structs

### ISSUE THREAD

**Issue by debugger84** [sqlc-dev/sqlc#2875]
### What do you want to change?

It would be nice to have the ability to return a resultset of joined tables as several structs in a row instead of a list of all fields.

For example, we have a query:

```
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL
);
CREATE TABLE posts (
  id   BIGSERIAL PRIMARY KEY,
  title text      NOT NULL,
  author_id int NOT NULL
);


-- name: ListAuthors :many
SELECT a.*, p.* FROM authors as a
JOIN posts as p ON p.author_id=a.id
ORDER BY name;

```

The result is presented as a struct:

```
type ListAuthorsRow struct {
	ID       int64
	Name     string
	ID_2     int64
	Title    string
	AuthorID int32
}
```

Desirable result:
```
type Author struct {
	ID   int64
	Name string
}

type Post struct {
	ID       int64
	Title    string
	AuthorID int32
}
type ListAuthorsRow struct {
	Author       Author
	Post Post
}
```

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by andrewmbenton** [comment]
Good news! This is exactly what `sqlc.embed()` is for: https://docs.sqlc.dev/en/stable/howto/embedding.html

**Comment by kevlarr** [comment]
@andrewmbenton I might have missed this elsewhere, but is there a way to get `sqlc.embed` to work with `LEFT OUTER` joins?
