### ISSUE TITLE
Package per model output

### ISSUE THREAD

**Issue by ewhauser** [sqlc-dev/sqlc#2890]
### What do you want to change?

When using sqlc with build systems that support conditional building of changed targets, sqlc's model of all output to a single directory output breaks conditional compilation. A single database change causes us to recompile and run all the tests for our entire application due to this.

sqlc should have an option that splits models into their own files and those files plus queries are put into their own directories.

### What programming language backends need to be changed?

Go, Python

**Comment by kyleconroy** [comment]
Thanks for the feature request. This is one of our most requested feature. Can you take a look over https://github.com/sqlc-dev/sqlc/issues/835 and https://github.com/sqlc-dev/sqlc/issues/1951 and see if they accurately describe what you're looking for?

**Comment by andrewmbenton** [comment]
I think this is actually kind of hard to do and maybe "impossible", if I understand your request correctly. It's hard for sqlc to know which queries "touch" which models. Obviously if a query returns a given model the answer is trivial, but what should sqlc do in cases of joins?

**Comment by ewhauser** [comment]
In thinking about this more, the best approach here is probably to shard individual SQL files into folders based on domain and only generate the models required using `omit_unused_structs`.
