### ISSUE TITLE
Add `MustExec` option

### ISSUE THREAD

**Issue by Goldziher** [sqlc-dev/sqlc#2906]
### What do you want to change?

Hiya,

I would like to ask for an option to dictate when a generated method should panic rather than return an error. Basically an equivalent to the golang regex `MustCompile` version.

**Comment by kyleconroy** [comment]
Thanks for the feature request and sorry for the slow response. 

This isn't something that we're looking to add to sqlc. If you'd like this functionality, I'd suggest forking github.com/sqlc-dev/sqlc-gen-go to add a `:mustexec` query tag.
