### ISSUE TITLE
sqlite/json: support -> and ->> operators

### ISSUE THREAD

**Issue by runsisi** [sqlc-dev/sqlc#2919]
### What do you want to change?

> Beginning with SQLite version 3.38.0 (2022-02-22), the -> and ->> operators are available for extracting subcomponents of JSON.[^1]

[^1]: 4.6. The -> and ->> operators
https://www.sqlite.org/json1.html#jptr

seems the latest sqlc v1.23 release does not support it:

https://play.sqlc.dev/p/25c82bb68f7a141175f4e51fd58047e1dc1466f61e02d059f5dcd6edf06a04d3

### What database engines need to be changed?

SQLite

### What programming language backends need to be changed?

Go

**Comment by orisano** [comment]
valid repro: https://play.sqlc.dev/p/73b7b8eb6ad22a3cceeb18db49bd99f377a1a707229c2a3486b58e5cc580311d
