### ISSUE TITLE
Can't install by using `go install`

### ISSUE THREAD

**Issue by imcvampire** [sqlc-dev/sqlc#2921]
### Version

1.23.0

### What happened?

1.23.0 can't be installed by `go install`. Seems like that version doesn't support Go 1.20 and older. 

### Relevant log output

```shell
go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
../../../go/pkg/mod/github.com/pingcap/tidb/parser@v0.0.0-20231010133155-38cb4f3312be/charset/charset.go:17:2: package cmp is not in GOROOT (/usr/local/Cellar/go@1.20/1.20.8/libexec/src/cmp)
../../../go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/analyzer/analyzer.go:8:2: package log/slog is not in GOROOT (/usr/local/Cellar/go@1.20/1.20.8/libexec/src/log/slog)
note: imported by a module that requires go 1.21
../../../go/pkg/mod/github.com/pingcap/tidb/parser@v0.0.0-20231010133155-38cb4f3312be/charset/charset.go:18:2: package slices is not in GOROOT (/usr/local/Cellar/go@1.20/1.20.8/libexec/src/slices)
```

### What operating system are you using?

Linux, macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by Juneezee** [comment]
> ```
> package log/slog is not in GOROOT (/usr/local/Cellar/go@1.20/1.20.8/libexec/src/log/slog)
> ```

The `log/slog` package was added in Go 1.21 [^1], and you are using Go 1.20. Update your Go to 1.21 and `go install` should work.

[^1]: https://tip.golang.org/doc/go1.21#slog
