### ISSUE TITLE
Panic from vet

### ISSUE THREAD

**Issue by WillAbides** [sqlc-dev/sqlc#2933]
### Version

1.23.0

### What happened?

vet panics on error from db.PrepareContext. It runs `s.Close()` when `s` is nil.

https://github.com/sqlc-dev/sqlc/blob/df4c05b6bc5fc8a84efa11ae2c2e636667fe426b/internal/cmd/vet.go#L335-L339

**Comment by andrewmbenton** [comment]
Thanks for the report, fix incoming. Did you run across this issue using sqlc managed databases, or your own database?

**Comment by WillAbides** [comment]
I ran into it trying out sqlite. The underlying issue was that I had the uri wrong. I found my way through that, but thought you would want to know about the panic.
