### ISSUE TITLE
plugin.GenerateRequest is internal

### ISSUE THREAD

**Issue by jpicht** [sqlc-dev/sqlc#3108]
### Version

1.25.0

### What happened?

I tried to write a plugin, but the imports in the example show it can only be done inside this repository, as the `GenerateRequest` is in `"github.com/sqlc-dev/sqlc/internal/plugin"` which cannot be used externally.

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
When creating a plugin, take a look at our existing https://github.com/sqlc-dev/sqlc-gen-go, https://github.com/sqlc-dev/sqlc-gen-kotlin, and https://github.com/sqlc-dev/sqlc-gen-python plugins. As you've discovered, you can't use the `github.com/sqlc-dev/sqlc/internal/plugin` package. Instead, you'll want to use the github.com/sqlc-dev/plugin-sdk-go module, which includes the plugin package and some additional helpers.
