### ISSUE TITLE
SQL formatter?

### ISSUE THREAD

**Issue by alecthomas** [sqlc-dev/sqlc#3171]
### What do you want to change?

I do want free unicorns!

But also, it just occurred to me that SQLC has one of the most robust SQL parsing systems I've seen, and it would be amazing if I could use it to consistently format my SQL for me. Just a thought.

**Comment by kyleconroy** [comment]
> I do want free unicorns!

There's no such thing as a free unicorn

> And it would be amazing if I could use it to consistently format my SQL for me

Agreed! SQL formatters are tricky to get right. CockroachDB has one, but I don't believe it's open-source. There's a popular one for PostgreSQL that's written in Perl, which is also a non-starter. If we wanted to do this, it would be some substantial work. I'm open to it, but it's not something we're going to prioritize now.
