### ISSUE TITLE
MySQL: Proper type for YEAR and TINYINT

### ISSUE THREAD

**Issue by Necoro** [sqlc-dev/sqlc#3201]
### Version

1.25.0

### What happened?

In issue #3088, `SMALLINT` was (correctly) changed from `int32` to `int16`. 
Surprisingly, `TINYINT`, which should have `int8`, has not been touched, resulting in the situation that `TINYINT` is now larger than `SMALLINT`.

Additionally, `YEAR` is checked for signed vs unsigned, even though this flag is not possible for MySQL: it should always result in an `uint16`.

FWIW: Closing this issue will also close #1856

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
@Necoro this is a good catch. We'll make sure to make this change before we release 1.26.
