### ISSUE TITLE
Using domain to create custom numeric data type leads to interface{}

### ISSUE THREAD

**Issue by joidegn** [sqlc-dev/sqlc#3324]
### Version

1.26.0

### What happened?

First time using `sqlc` so I might be missing sth obvious.

I am trying to use the following domain.

`CREATE DOMAIN big_precise_numeric AS NUMERIC(16,5);`

When applying it on a column I get an `interface{}` as the struct field. When I check what happened with `SQLCDEBUG=dumpexplain=1 ` I get `unknown PostgreSQL type: big_precise_numeric`

When I use a `NUMERIC(16, 5)` directly then all is well and the struct field is of type NullString which makes sense.

### Relevant log output

```shell
SQLCDEBUG=dumpexplain=1 sqlc generate
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
2024/04/05 17:21:49 unknown PostgreSQL type: big_precise_numeric
```

### Database schema

```sql
CREATE DOMAIN big_precise_numeric AS NUMERIC(16,5);

CREATE TABLE test (
    id SERIAL PRIMARY KEY,
    value big_precise_numeric
);
```

### SQL queries

```sql
-- name: GetTest :one
SELECT * FROM test
WHERE id = $1 LIMIT 1;

-- name: ListTest :many
SELECT * FROM test;

-- name: CreateTest :one
INSERT INTO test (
  value
) VALUES (
  $1
)
RETURNING *;

-- name: DeleteTest :exec
DELETE FROM test
WHERE id = $1;
```

### Configuration

```yaml
version: "2"
sql:
  - gen:
      go:
        out: "db"
        emit_interface: true
        omit_unused_structs: true
    schema: "schema/"
    queries: "sql/"
    engine: "postgresql"
```

### Playground URL

https://play.sqlc.dev/p/15063d999f89198faf5ed1f1604b21662288168a522390831d7f5bbf6dda25ec

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by joidegn** [comment]
Closing because the documentation mentions that only specific postgres types are supported.

I solved it by explicitly using the column name to override the go type.

**Comment by theneva** [comment]
For what it's worth, I was surprised today by the fact that type overrides don't support domain types :smile:
