### ISSUE TITLE
Does it support logging of executed SQL?

### ISSUE THREAD

**Issue by zzhaolei** [sqlc-dev/sqlc#3362]
### What do you want to change?

Does it support logging of executed SQL? For debugging

like query sql:`select * from author where id = ? and name = ?;`

output the actual sql: `select * from author where id = 6 and name = 'test';`

### What database engines need to be changed?

PostgreSQL, MySQL, SQLite

### What programming language backends need to be changed?

Go

**Comment by aseerkt** [comment]
I think logging is out of scope from the purpose that sqlc provides.

**Comment by nmsobri** [comment]
> I think logging is out of scope from the purpose that sqlc provides.

Yeah it outside of the scope of sqlc.. But sqlc should provide facility to do this.. maybe some sort of hook?
