### ISSUE TITLE
Add Ruby support

### ISSUE THREAD

**Issue by doron050** [sqlc-dev/sqlc#3390]
The ruby ecosystem is very much alive, you can see it in [Ruby 2023 ecosystem report by Jetbrains](https://www.jetbrains.com/lp/devecosystem-2023/ruby/ ), and as a developer and an SQLC user, I think the project can benefit by supporting as many language runtimes as possible + if there is Python, why not Ruby? :) 

@SockworkOrange and I are close to releasing the 1st (though mature) version of our C# plugin, and we want to start working on a ruby one.

**Comment by SockworkOrange** [comment]
Considering this comment on the corresponding C# issue - 
"if someone would like to try their hand at C# support, you aren't blocked getting your changes into the sqlc codebase"

@doron050 and I have also started working on adding Ruby support (implemented in Ruby) in here - https://github.com/DaredevilOSS/sqlc-gen-ruby

**Comment by kyleconroy** [comment]
Really excited to see this one happen as well. I was going to use https://github.com/jeremyevans/sequel to power it, but honestly haven't put too much thought into the design. Can't wait!

**Comment by SockworkOrange** [comment]
Our approach in the C# plugin was the officially maintained libs per db (in MySQL for example), or simply the lightweight, most popular lib.
I think that adding an additional ORM abstraction like sequel kinds beats the purpose, no? The comment on using Dapper for C# [here](https://github.com/sqlc-dev/sqlc/issues/373#issuecomment-1246887564) summarizes it well.

For example in Ruby, I thought of using:
* mysql2 for MySQL (see [here](https://dev.mysql.com/doc/refman/8.4/en/apis-ruby.html))
* pg for PostgreSQL (see [here](https://rubygems.org/gems/pg))
* sqlite3 for Sqlite (see [here](https://rubygems.org/gems/sqlite3))

@doron050

**Comment by SockworkOrange** [comment]
Released first version in [here](https://github.com/DaredevilOSS/sqlc-gen-ruby/releases/tag/0.10.0), supporting MySQL & Postgres databases, and genrating Ruby3 compatible code.

**Comment by SockworkOrange** [comment]
@kyleconroy can be closed then:)
