### ISSUE TITLE
Can WASM plugins read local files?

### ISSUE THREAD

**Issue by fdietze** [sqlc-dev/sqlc#3517]
Hi, I'm thinking about writing a wasm plugin. I was wondering if those plugins can somehow read a local file from where I'm executing `sqlc generate`. Or is there another way I can pass a file to the generator?

**Comment by orisano** [comment]
You can use file:// to browse like this.
https://github.com/orisano/sqlc-gen-ts-d1/blob/82f35cb7c0d74d4d18539df344899f0e9a745608/sqlc.json#L7

**Comment by fdietze** [comment]
I think there is a misunderstanding.

I was asking if the code running in wasm can access a local file. Can I pass a file to the program running in wasm?

**Comment by orisano** [comment]
Currently, this is not possible with sqlc.

**Comment by fdietze** [comment]
Thank you!
