### ISSUE TITLE
postgres ARRAY of a TYPE becomes plain []interface{}

### ISSUE THREAD

**Issue by kayshav** [sqlc-dev/sqlc#3529]
### Version

1.27.0

### What happened?

I have the following in my ddls.sql  
```
CREATE TYPE myschema.obj_ref AS  (
    obj_id nonnull_int8,
    obj_type nonnull_string
);
```

I use this in another table as:

```
CREATE TABLE myschema.site (
  //...
  deployments obj_ref ARRAY
};
```

However, in the generated model code the obi_ref type is not used at all, Instead I see
```
type myschemaSite struct {
 deployments []interface{}             <----- The obj_ref type is not used at all
}
```

Is there something wrong in the way my schema is defined?  

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kayshav** [comment]
Found a workaround

**Comment by beanbocchi** [comment]
How did you do?
