### ISSUE TITLE
Set running environment (dev or prod) with `sqlc generate`

### ISSUE THREAD

**Issue by aarcex3** [sqlc-dev/sqlc#3635]
### What do you want to change?

This is more of a question. Is it possible to have two sqlc.yaml files? One for development and one for production?
In my case I'm developing an app using sqlite, but later I want to deploy it with postgres.

Something like this:
- For a sqlc.dev.yaml file
```bash
sqlc generate --dev
```

- sql.prod.yaml for production
```bash
sqlc generate
```

Or maybe tell sqlc what file to read when running it.

```bash
sqlc generate file.yaml
```

**Comment by kyleconroy** [comment]
Yes, you can pick a different configuration file by passing the [`-f` or `--file` flag](https://docs.sqlc.dev/en/latest/reference/cli.html).
