### ISSUE TITLE
Support different parameter tags

### ISSUE THREAD

**Issue by adamgen** [sqlc-dev/sqlc#3685]
### What do you want to change?

Currently the sql accepts arguments using native sql notation `$1`.

Additionally I'd like to have a different parameter notation, for example pyformat `%(my_param)s`

To be more explicit - currently that's the only way to pass an argument

```
select *
from users
where id = $1
```

This is how I'd like to pass an argument

```
select *
from users
where id = %(id)s
```

**Comment by kyleconroy** [comment]
We support the database's native parameter format, usually `?` or `$1`. In addition we also support the `sqlc.arg` macro, which is [documented here](https://docs.sqlc.dev/en/latest/howto/named_parameters.html). Support that macro has proved difficult enough that I have no plans to add additional parameter tags right now.
