### ISSUE TITLE
SLQC doesn't support vectors for MYSQL

### ISSUE THREAD

**Issue by mcgold1** [sqlc-dev/sqlc#3732]
### Version

1.27.0

### What happened?

Mysql added vector columns in MySQL 9.0.  When trying to use SQLC with a vector column in the parser doesn't recognize it and throws a syntax error.

### Database schema

```sql
CREATE TABLE t1(
    id INT PRIMARY KEY auto_increment,
    embedding VECTOR(4)
);
```

### SQL queries

```sql
INSERT INTO t1(embedding) VALUES (STRING_TO_VECTOR('[0.1, 0.2, 0.3, 0.4]'));

SELECT id FROM t1 ORDER BY DISTANCE(STRING_TO_VECTOR('[1.2, 3.4, 5.6]'), embedding, 'L2_squared') LIMIT 10;
```

**Comment by kyleconroy** [comment]
Could you please include an example schema and query? I'm not familiar with the new vector type.

**Comment by mcgold1** [comment]
@kyleconroy Added an example schema and a couple of query examples.  Additionally here's the MySQL 9.1 vector function doc page which may come in handy: https://dev.mysql.com/doc/refman/9.1/en/vector-functions.html.
