### ISSUE TITLE
Represent postgres bytea[] type with pq.ByteaArray

### ISSUE THREAD

**Issue by mmcloughlin** [sqlc-dev/sqlc#419]
I just encountered a problem inserting data into a postgres `bytea[]` array type. I was able to solve it by configuring a type override to use [`pq.ByteaArray`](https://godoc.org/github.com/lib/pq#ByteaArray) instead of `[][]byte`. It seems this special case should probably be implemented in `sqlc`.

Thanks for your work on this, it's exactly the middle ground between `database/sql` and `gorm` that I was looking for.

**Comment by kyleconroy** [comment]
Interesting. This is caused because [pq.Array](https://github.com/lib/pq/blob/v1.3.0/array.go#L29) does not have an entry for `pg.ByteArray`.

**Comment by andrewmbenton** [comment]
Closing because an entry was added to `lib/pq` as of v1.9.0 in Dec 2020: https://github.com/lib/pq/pull/876/files
