### ISSUE TITLE
Support validating GROUP BY clause

### ISSUE THREAD

**Issue by dharmjit** [sqlc-dev/sqlc#438]
I am not sure whether this check will come under validations performed at sqlc.  The code generation doesn't check whether the `Group BY` clause is present or not correct
For Below schema
```
CREATE TABLE IF NOT EXISTS products_equipments (
    product_id VARCHAR NOT NULL ,
    equipment_id VARCHAR NOT NULL,
    value INETGER NOT NULL
);
```
Below query successfully creates code
```
SELECT p.equipment_id,count(p.product_id) from products_equipments p
WHERE
p.equipment_id = $1;
```
And true for below as well
```
SELECT p.equipment_id,p.product_id,sum(p.value) from products_equipments p
WHERE
p.equipment_id = $1
GROUP BY p.equipment_id;
```

**Comment by kyleconroy** [comment]
> I am not sure whether this check will come under validations performed at sqlc.

sqlc doesn't support `GROUP BY` yet. Soon!

**Comment by kyleconroy** [comment]
Support was added a few version ago for validating group by clauses by default.
