### ISSUE TITLE
sqlc generates multiple Go types with same name

### ISSUE THREAD

**Issue by kevinburke1** [sqlc-dev/sqlc#588]
I had this

```
CREATE TYPE controller_event AS enum( ... )

CREATE TABLE controller_events ( ... )
```

Both of these generate a `ControllerEvent` struct in Go. It would probably be better if sqlc detected the fact that duplicate entries were being generated, and errored out instead of writing a config file.

**Comment by kyleconroy** [comment]
> It would probably be better if sqlc detected the fact that duplicate entries were being generated, and errored out

Agreed! This should actually be pretty easy, as all types are generated in the same package.

**Comment by kyleconroy** [comment]
```
CREATE TYPE role AS ENUM ('write', 'read');

CREATE TABLE roles (
  id           UUID                    PRIMARY KEY DEFAULT gen_random_uuid (),
  create_time  TIMESTAMPTZ             NOT NULL    DEFAULT CURRENT_TIMESTAMP,
  update_time  TIMESTAMPTZ             NOT NULL    DEFAULT CURRENT_TIMESTAMP,
  role         role                    NOT NULL,
);
```

**Comment by bgentry** [comment]
Would this be solved by adding config options to override the generated Go type name for a table? That's something I'm wanting to do anyway for another reason (we have a table name that we use a shorthand for in application code).

**Comment by andrewmbenton** [comment]
> Would a workaround be to add a config option to override the generated Go type name for a table? That's something I'm wanting to do anyway for another reason (we have a table name that we use a shorthand for in application code).

A rename entry would work for your case probably. In the duplicate name case it wouldn't work since both generated names are the same.

**Comment by coolaj86** [comment]
**Update**: I was able to solve this by targeting the column name `state` and renaming it to `StateName`. Fortunately no other columns or tables were named `state`, so this global approach happened to work.

I've run into a case where a `rename` doesn't seem to work. There's an enum `task.state` and a table `task_state` and it can't seem to differentiate between the two even with a rename:

This is the config:

```yaml
version: '2'
sql:
  - engine: 'mysql'
    schema: './mariadb/schema/'
    queries: './mariadb/queries/'
    gen:
      go:
        package: 'v1db'
        out: 'mariadb/v1db'
        emit_json_tags: true
        rename:
          state: 'StateName' # ALL identifiers named 'state' are renamed
          task.state: 'TaskStateEnum' # ignored
          task_state: 'TaskStates' # no-op
```

This is the structure:

```sql
CREATE TABLE `task` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(10) unsigned NOT NULL,
  `template_id` int(10) unsigned NOT NULL,
  `status_id` int(10) unsigned NOT NULL,
  `values` longtext NOT NULL DEFAULT '{}',
  `state` enum('incomplete','pending','processing','completed') DEFAULT 'incomplete',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `account_task_account_id_foreign` (`account_id`),
  KEY `account_task_task_id_foreign` (`template_id`),
  KEY `account_task_status_id_foreign` (`status_id`),
  CONSTRAINT `account_task_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`) ON DELETE CASCADE,
  CONSTRAINT `account_task_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `status` (`id`) ON DELETE CASCADE,
  CONSTRAINT `account_task_task_id_foreign` FOREIGN KEY (`template_id`) REFERENCES `task_template` (`id`) ON DELETE CASCADE
)

CREATE TABLE `task_state` (
  `slug` varchar(255) NOT NULL,
  `enum` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  `icon` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`slug`),
  UNIQUE KEY `task_state_enum_unique` (`enum`)
)
```

Either way, I get errors:

```
error generating code: struct name conflicts with enum name: TaskState
error generating code: struct name conflicts with enum name: TaskStates
```
