### ISSUE TITLE
Mariadb INSERT...RETURNING Support

### ISSUE THREAD

**Issue by ghost** [sqlc-dev/sqlc#693]
Hi.

Okay, so I am not one to make issues, usually.

sqlc as a tool has really helped me enjoy writing database related code for quite a while now. I personally use postgres and that is great. However, for my work, we use mariadb, and every time I write an insert or update query without the RETURNING clause, it feels very wrong and inefficient.

Since mariadb 10.5, it has supported [INSERT...RETURNING](https://mariadb.com/kb/en/insertreturning/).

Anyway, I also want to thank everyone who contributed to this tool. There are not many tools I get excited for each new release.

**Comment by kyleconroy** [comment]
Thanks for the feature request. I have never used MariaDB and was under the assumption it was the exact same as MySQL. It sounds like that used to be the case, but recent releases have added new features that MySQL doesn't have. The parser we use for MySQL (https://github.com/pingcap/parser) doesn't support RETURNING. I'll have to take a look at some of the other parsers out there to see what we can use.

**Comment by meutraa** [comment]
The pingcap/parse project does seem to support mariadb specific features.

For example: https://github.com/pingcap/parser/pull/337
Not RETURNING though.

**Comment by kyleconroy** [comment]
It doesn't seem like the pingcap parser is going to support RETURNING, so I'm going to close this as won't fix. Happy to support it once it's added there.
