### ISSUE TITLE
Support passing slices to MySQL queries

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#695]
While MySQL supports the ANY operator, it does not support arrays. This means the [currently documented way](https://github.com/kyleconroy/sqlc/blob/master/docs/any.md) to pass slices to a query will not work.

**Comment by kyleconroy** [comment]
Here's some related discussion from the go-sql-driver repository:
* https://github.com/go-sql-driver/mysql/issues/107
* https://github.com/go-sql-driver/mysql/issues/176

**Comment by kyleconroy** [comment]
The [MEMBER OF](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of) syntax may offer a solution. The problem is that you need to encode the slice as JSON before passing it into the query.

```sql
CREATE TABLE pkg (
  id text NOT NULL,
  vic VARCHAR(50) NOT NULL,
  kim text NOT NULL,
  order INTEGER NOT NULL,
  PRIMARY KEY (id)
);

/* name: GetPkgID :many */
SELECT id, vic, kim FROM pkg
WHERE vic MEMBER OF (?) AND shop_id = ?;
```

**Comment by kyleconroy** [comment]
Okay, here's my current idea. We add a second type parameter to `sqlc.arg`. That parameter, if passed, will compile to a cast statement. We can support the ARRAY type syntax in this type parameter and generate the correct code.

```sql
CREATE TABLE users (id SERIAL);

-- name: FilterUsers :many
SELECT * FROM users
WHERE id MEMBER OF(sqlc.arg('ids', 'SERIAL ARRAY'));
```

```go
const filterUsers = `-- name: FilterUsers :many
SELECT id FROM users
WHERE id MEMBER OF(CAST(? AS JSON));
`

func (q *Queries) FilterUsers(ctx context.Context, ids []int64) ([]User, error) {
	// ...
}
```

A few issues I can think of:
* The array type must convert to a scalar type that can be represented inside a JSON array
* We'd need to generate a helper method that converts slices to JSON
* We'd probably also need to add a method that unmarshals JSON as well

**Comment by warent** [comment]
I'm not sure if it's bad practice, but maybe the generated code could produce a dynamic query, generating N placeholders for each array value. So, something like:

```go
func filterUsers(vals int[])
{
return fmt.Sprintf(`-- name: FilterUsers :many
SELECT id FROM users
WHERE id MEMBER OF(?%v);
`, strings.Repeat(",?", len(inValues)-1));
}
```

**Comment by yeka** [comment]
Just throwing an idea (or hack) regarding `IN` statement in SQL.


Current behaviour:
```
const listAuthors = `-- name: ListAuthors :many
SELECT id, name FROM authors WHERE id IN($1) AND name = $2;
`

type ListAuthorsParams struct {
	ID   int 
	Name string
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, arg.ID, arg.Name)
```

My idea is to change the parameter into slice and expanding the query based on the size of the slice.
What I meant by expanding is to replace `id IN ($1)` into `id IN($1, $2, $3, ...)`.
If there's 3 ids, `name = $2` will become `name = $4`.
Using the same query, the generated code will now look like this:

```
type ListAuthorsParams struct {
	ID   []int 
	Name string
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	query, args := q.expand(listAuthors, expandArg{arg.ID}, arg.Name)
	rows, err := q.db.QueryContext(ctx, query, args...)
```

The `expandArg` type is used to differentiate normal slice with slice from `IN` statement.
The `q.expand()` function will return modified query and args.

For example, given that ```arg = ListAuthorsParams{[]int{9, 8, 6, 7}, "Joe"}```, `q.expand()` will return:
```
query = "SELECT id, name FROM authors WHERE id IN($1, $2, $3, $4) AND name = $5;"
args = []interface{}{9, 8, 6, 7, "Joe"}
```

The code for `q.expand()` can be seen [here](https://github.com/yeka/sqlc/compare/master...feature/in). I haven't managed to find how to change `arg.ID` into `[]int`.

Not forget to mention, this solution will not work for prepared statement.

**Comment by mightyguava** [comment]
How about for MySQL only, `( ? )` will be interpreted as accepting a list of items of that type, rather than a single one?

**Pros**

* It's still valid SQL
* It would not be confusing to users. As in previous issues like https://github.com/kyleconroy/sqlc/issues/706, https://github.com/go-sql-driver/mysql/issues/107, https://github.com/go-sql-driver/mysql/issues/176, people naturally assume you can pass in a slice. Any strongly-typed language will prevent you from passing in a single value.

**Cons**

* The type of the binding differs from what you'd have to pass in to the driver, but sqlc already abstracts the driver away so that's fine.
* What would you do about `(?, ?, ?)` etc...? Imo sqlc could just error in the parse stage and say that you have to write your query as a single `(?)`

**Comment by namndev** [comment]
> ```sql
> MEMBER
> ```

Syntax error with keyword `MEMBER OF` ? I use sql 1.6.0.

**Comment by namndev** [comment]
I have an idea,

using [FIND_IN_SET](https://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_find-in-set)

```
SELECT id FROM users
WHERE FIND_IN_SET(id, ?)
```

But name of variable after run `sqlc generate`: FINDINSET and FINDINSET_2, ...
@kyleconroy, How to fix or rename variable in above?

**Comment by fr3fou** [comment]
How can I achieve this in postgres?

**Comment by xiazemin** [comment]
> Just throwing an idea (or hack) regarding `IN` statement in SQL.
> 
> Current behaviour:
> 
> ```go
> const listAuthors = `-- name: ListAuthors :many
> SELECT id, name FROM authors WHERE id IN($1) AND name = $2;
> `
> 
> type ListAuthorsParams struct {
> 	ID   int 
> 	Name string
> }
> 
> func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
> 	rows, err := q.db.QueryContext(ctx, listAuthors, arg.ID, arg.Name)
> ```
> 
> My idea is to change the parameter into slice and expanding the query based on the size of the slice.
> What I meant by expanding is to replace `id IN ($1)` into `id IN($1, $2, $3, ...)`.
> If there's 3 ids, `name = $2` will become `name = $4`.
> Using the same query, the generated code will now look like this:
> 
> ```go
> type ListAuthorsParams struct {
> 	ID   []int 
> 	Name string
> }
> 
> func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
> 	query, args := q.expand(listAuthors, expandArg{arg.ID}, arg.Name)
> 	rows, err := q.db.QueryContext(ctx, query, args...)
> ```
> 
> The `expandArg` type is used to differentiate normal slice with slice from `IN` statement.
> The `q.expand()` function will return modified query and args.
> 
> For example, given that `arg = ListAuthorsParams{[]int{9, 8, 6, 7}, "Joe"}`, `q.expand()` will return:
> 
> ```go
> query = "SELECT id, name FROM authors WHERE id IN($1, $2, $3, $4) AND name = $5;"
> args = []interface{}{9, 8, 6, 7, "Joe"}
> ```
> 
> The code for `q.expand()` can be seen [here](https://github.com/yeka/sqlc/compare/master...feature/in). I haven't managed to find how to change `arg.ID` into `[]int`.
> 
> Not forget to mention, this solution will not work for prepared statement.

i fufill  a version that solve this problem https://github.com/xiazemin/sqlc

**Comment by asterikx** [comment]
Is there a workaround for the time? Listing by IDs seems to be a rather crucial thing to do after all

**Comment by ericraio** [comment]
> Is there a workaround for the time? Listing by IDs seems to be a rather crucial thing to do after all, e.g. for pre-loading associations

The only work around I ended up doing was creating a separate file that shares the same package name and writing the golang code manually :/

**Comment by xiazemin** [comment]
> > Is there a workaround for the time? Listing by IDs seems to be a rather crucial thing to do after all, e.g. for pre-loading associations
> 
> The only work around I ended up doing was creating a separate file that shares the same package name and writing the golang code manually :/

my fork solved this issue https://github.com/xiazemin/sqlc

**Comment by xiazemin** [comment]
and the example of https://github.com/xiazemin/sqlc is here https://github.com/xiazemin/sqlc_study

**Comment by ericraio** [comment]
hey @xiazemin this is great! Just read your previous messages also, maybe you can make a proposal or pull request to this repo?

**Comment by koolay** [comment]
@kyleconroy Hi, any plan to support slice?

**Comment by muir** [comment]
A good solution to this is crucial.  There is an acceptable solution for the postgres driver using pg.Array() but in the comment thread above there was nothing that really works for mysql.  In the meantime, I'll fall back to using a query generator like squirrel but that's not my first choice.

**Comment by ericraio** [comment]
I've been using a forked version of sqlc where they implemented `sqlc.slice()` and all it does is a string replace in the generated code. Not ideal but works really good and would prefer that we had this then not having the feature at all.

**Comment by xiazemin** [comment]
my fork also support insert into xxx values xxx， where values is a slice,you can try it!

**Comment by ksthiele** [comment]
I haven't tried it yet, but would something like that work for a temporary solution?

```
SELECT id FROM authors
WHERE id IN (@list = ?);
```

**Comment by ksthiele** [comment]
I don't know, wouldn't it make sense to always treat a value in IN() as a slice?

**Comment by xiazemin** [comment]
https://github.com/xiazemin/sqlc

**Comment by ericraio** [comment]
Xiazemin, your sqlc repo renames everything and is not a true fork, your code can’t be migrated back into the main repository.

**Comment by yeomc-quasar** [comment]
When will this feature be updated?

**Comment by link-duan** [comment]
```sql
SELECT * FROM a_table WHERE (a, b) in (?);
```

How to implement this case in sqlc?

**Comment by SebastienMelki** [comment]
Hello, this seems like a pretty important feature to have. Anybody have a plan to implement this? If somebody can point me to the correct place I can try submitting a PR. 

Thanks

**Comment by chengjun-suger** [comment]
It works in Postgresql 

```
-- name: BatchUpdateUsageRecordGroupStatus :exec
UPDATE metering.usage_record_group 
SET status = $2, last_update_time = CURRENT_TIMESTAMP 
WHERE organization_id = $1 AND id = ANY(@ids::text[]);
```

**Comment by gmhafiz** [comment]
Thanks @chengjun-suger I tried with

```sql
-- name: SelectWhereInLastNames :many
SELECT * FROM users WHERE last_name = ANY(@last_name::text[]);
```

and it generates
```go
import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
)

const selectWhereInLastNames = `-- name: SelectWhereInLastNames :many
SELECT id, first_name, middle_name, last_name, email, password, favourite_colour FROM users WHERE last_name = ANY($1::text[])
`

func (q *Queries) SelectWhereInLastNames(ctx context.Context, lastName []string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, selectWhereInLastNames, pq.Array(lastName))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.FavouriteColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

**Comment by zc2638** [comment]
I see this issue discussed for nearly two years, is there a solution or a plan in the near future, which will determine whether my project can choose to use sqlc instead of others, such as gorm.
Thanks.

**Comment by karatekaneen** [comment]
Really want this feature as well and started to think about an alternative approach to the problem.

_Not sure if this is possible in the way sqlc works, I'm just putting the idea out there to start a discussion._
If we can somehow identify where in the query the problem is and we can modify the query accordingly. One approach to this would be to add some kind of "variadric" configuration based on index

For example, take the following query:

```sql
-- name: FindThings :many :variadric(0)
SELECT * 
FROM a_table 
WHERE status IN ( ? )
AND created_at > ?
```

This would tell sqlc that the first `?` is actually a slice of values and would change the generated function to instead expecting `T` actually expect `[]T` and when calling to do the query it uses the same approach as mentioned [here](https://github.com/go-sql-driver/mysql/issues/176#issuecomment-29065022) to replace the first `?` with the number of items in the slice passed in.

Would this be possible with the current approach? And if so, does anyone know where to start?

**Comment by karatekaneen** [comment]
@LIQRGV Interesting, going to have a deep dive in the code on Monday to see what you've done. 
The syntax with `???` is a much better idea imo, only drawback is that it's not valid SQL anymore(?). 

Currently looking to doing something similar to what you've done but as a plugin, but haven't decided anything yet.

**Comment by LIQRGV** [comment]
> only drawback is that it's not valid SQL anymore(?)

Yep, @karatekaneen technically it's not a valid SQL anymore since it'll parse the query into another placeholder depend on the number args passed.
So if you have 2 params, it will become 
`WHERE x_column IN (?,?)`

Anyway, do you know how to use `IN` keyword on normal SQL ? I mean using it on prepared statement.
Maybe I can make it to comply with SQL standard.

**Comment by FrancoisPrigent** [comment]
[FIND_IN_SET](https://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_find-in-set) does the job

**Comment by mrngm** [comment]
This waits for #1816 to be reviewed and merged.

**Comment by kyleconroy** [comment]
https://docs.sqlc.dev/en/stable/reference/macros.html#sqlc-slice

Adding a link to the docs for future folks

**Comment by YvanDaSilva** [comment]
@kyleconroy https://github.com/sqlc-dev/sqlc/issues/2002 was marked as a duplicate of this issue.
However, it seems it isn't.

#2002 concerns multiple inserted values. sqlc.slice can't be used for that purpose as it replaces name by multuplie escaped params entries of type string.

We have this other issue https://github.com/sqlc-dev/sqlc/issues/3305 that is open that explains it better IMHO.
https://play.sqlc.dev/p/7bfa28e99e0207fb0c7d2b457ccc452674daa60acb5bccea336d7c3de293b220
