### ISSUE TITLE
Option for Context-free and Pointer returning struct

### ISSUE THREAD

**Issue by kokizzu** [sqlc-dev/sqlc#812]
Currently the generated values are:
```
func (q *Queries) BuffById(ctx context.Context, id int64) (Buff, error) {
```

it would be nice if there's option to set these values:
```
   emit_context: false
   emit_pointer: true
```

so it would generate something like this:
```
func (q *Queries) BuffById(id int64) (*Buff, error) {
```

**Comment by maratori** [comment]
Can you add use case of `emit_pointer: true`, please?

**Comment by kokizzu** [comment]
when the struct is large (>word size of the compiler/os/processor), it's inefficient to copy everything by value (not using pointer), copy by pointer/reference is [faster](https://stackoverflow.com/questions/23542989/pointers-vs-values-in-parameters-and-return-values).

**Comment by andrewmbenton** [comment]
Closing this as it's quite old and we already have `emit_result_struct_pointers`. To remove context from generated output I'd suggest forking and modifying [sqlc-gen-go](https://github.com/sqlc-dev/sqlc-gen-go), which is just sqlc's internal codegen package extracted into an external plugin.
