### ISSUE TITLE
append goose_db_version table to list of tables if you are using goose for migrations

### ISSUE THREAD

**Issue by kevinburke1** [sqlc-dev/sqlc#900]
It would be nice to be able to do operations on the goose_db_version table, which I'm currently doing by hand.

**Comment by kyleconroy** [comment]
Can you write a `CREATE TABLE` for the goose_db_version table? And then just put it in a directory that won't be picked up by your migrations? That way we don't have to code any Goose-specific logic into sqlc.

**Comment by kevinburkemeter** [comment]
I guess, it's just... you know I'm using goose, this means I'd need to keep a copy of the Goose schema in addition to the schema that you have.

**Comment by kevinburkemeter** [comment]
Like I could use the same trick to implement `pg_tables` but it kinda seems like sqlc should add that?

**Comment by mfridman** [comment]
Curious, why would `sqlc` need to know the goose schema? That schema is an implementation detail of the individual project and may change overtime.

As a curiosity I'm curious what operations you'd even be running against that goose table @kevinburke1.

I'm wondering if there is something goose could do to help. Maybe allow a zero-based migration file that never gets picked up by goose but is available to sqlc to generate the resulting table.

**Comment by kyleconroy** [comment]
The system catalog and information schema are built in. The goose table is created by Goose. I don't want to tie sqlc to a specific version of goose. 

Adding a CREATE TABLE statement for that table is a fine workaround.
