### ISSUE TITLE
Need more examples for querying with string arguments. "Error 1054: Unknown column '$1' in 'field list'"

### ISSUE THREAD

**Issue by rw3iss** [sqlc-dev/sqlc#906]
Hi, I'm trying to follow the documentation here, using mysql driver:
https://docs.sqlc.dev/en/latest/howto/insert.html

It seems these examples use the number argument format, ie. $1, $2 etc... as opposed to the question mark format, ie. ? as shown here: https://github.com/kyleconroy/sqlc/blob/master/examples/authors/mysql/query.sql

Using mysql, is one of these the preferred way? It seems the queries do not compile for me if I use the question marks.

However, when using the number format, I can't seem to execute the queries. There are also no examples in the documentation that state if we must surround string arguments in quotes, or if they'll be automatically escaped... ?

Here is my sql:

```
-- users.sql

-- name: GetUserById :one
SELECT * FROM users
WHERE id = $1 LIMIT 1;

-- name: GetUserByEmail :one
SELECT * FROM users
WHERE email=$1 LIMIT 1;

-- name: GetUserByUsername :one
SELECT * FROM users
WHERE username=$1 LIMIT 1;

-- name: CreateUser :exec
INSERT INTO users (
  username, email
) VALUES (
  $1, $2
);
```

When I call these methods, ie:
```
err := q.CreateUser(ctx, data.CreateUserParams{
	Username: "rw3iss",
	Email:    "rw3iss@gmail.com",
})
if err != nil {
	log.Print("Error inserting %s", err)
}

fmt.Printf("Looking for new user...")
user, err := q.GetUserByUsername(ctx, "rw3iss")
if err != nil {
	log.Print("Error querying %s", err)
}
```

It does not produce an error on the create, however, no new record seems to be inserted. The GetUserByUsername query produces the following error:

> Looking for new user...Error:  
> Local: http://localhost:4501
> 2021/02/23 01:39:12 Error inserting %sError 1054: Unknown column '$1' in 'field list' 

Can you please advise the correct way to structure queries with string arguments, and maybe update the documentation to provide examples for such cases?

**Comment by vvalkonen** [comment]
Shouldn't you be using `?` as placeholders instead of `$1` which is a PostgreSQL parameter placeholder?
