### ISSUE TITLE
is unnest supported?

### ISSUE THREAD

**Issue by tcastelly** [sqlc-dev/sqlc#958]
Hello,

Is allowed to use unnest?

```sql
INSERT INTO inventory(id, json_row, name)
SELECT *
FROM unnest(Array[48]::int[], ARRAY['{}']::json[], ARRAY['me']::varchar[]);
```

I have this error:
> function unnest(unknown, unknown) does not exist

It's maybe a duplicate issue for:
https://github.com/kyleconroy/sqlc/issues/670

But the error message is not the same anymore.

Thank you very much.

**Comment by tcastelly** [comment]
Thank you for your answer.

I can compile your query.
In fact I can compile this:
```sql
SELECT unnest(ARRAY[48]::int[])
```

But because I need multiple arrays in `unnest` it looks like I have to use:
```sql
SELECT * FROM unnest(ARRAY[48]::int[], ARRAY['{}']::json[]);
```

and here it's broken:
> function unnest(unknown, unknown) does not exist

**Comment by maratori** [comment]
Have you tried multiple `unnest`s for multiple arrays? Something like this should work:
```sql
-- name: InsertOutdatedEntity :exec
INSERT INTO outdated_entities (entity_type, entity_id, outdated_at)
SELECT unnest(@entity_types::VARCHAR[]), unnest(@ids::UUID[]), @outdated_at;
```

**Comment by tcastelly** [comment]
Oh yes thank you :)

**Comment by tcastelly** [comment]
I'm sorry to re-open this old issue. But it seems than the "unnest" example from the Postgres documentation is not working with `sqlc`.
I'm wondering if it's something can be fixed or no.

https://www.postgresql.org/docs/current/functions-array.html
```sql
select * from unnest(ARRAY[1,2], ARRAY['foo','bar','baz']) as x(a,b);
```
result: https://play.sqlc.dev/p/29816032c2fa5f604524ad3089121ef2284bf59c84d871ede995f78bcd4f11c1

Thank you very much.

**Comment by carlmjohnson** [comment]
I have had this same issue. My workaround was to use JSONB instead of a pair of ARRAYs, but it's ugly.

**Comment by tcastelly** [comment]
> I have had this same issue. My workaround was to use JSONB instead of a pair of ARRAYs, but it's ugly.

Hi @carlmjohnson do you have an example? Because I've tried something like this but it's not working

```sql
WITH to_update as (
    SELECT x
    FROM JSON_TO_RECORDSET(@auth_users::JSON)
             AS x("id" BIGINT, "label" VARCHAR(55))
)
UPDATE auth_users
SET label = to_update.label
FROM to_update
WHERE auth_users.id = to_update.id
  AND auth_users.user_id = @user_id;
```

Issue: https://github.com/kyleconroy/sqlc/issues/2191

Thanks you :)

**Comment by carlmjohnson** [comment]
https://github.com/spotlightpa/almanack/blob/d48b9e2167754e56b729788fe04d1270f00c38af/sql/queries/gdocs_image.sql#L6

**Comment by kyleconroy** [comment]
Going to close this out as we have a pretty good workaround.

**Comment by yihaoye** [comment]
beside jsonb_array, there are another 2 way which maybe better in performance if array too large for json marshal in code

postgresql 10+ could do the following uses parallel arrays evaluated in lockstep, it will return `[(1, a), (2, b), (3, null), (4, null)]`
```sql
SELECT 
    unnest(ARRAY[1, 2, 3, 4]) as id, 
    unnest(ARRAY['a', 'b']) as name;
```

there is 3rd way to work around by `WITH ORDINALITY ` + `JOIN`

```sql
WITH pairs AS (
  SELECT 
    a.val::bigint AS num,
    b.val::uuid AS id,
    c.val::varchar AS description
  FROM unnest(@array_a::bigint[]) WITH ORDINALITY AS a(val, ord)
  JOIN unnest(@array_b::uuid[]) WITH ORDINALITY AS b(val, ord) ON a.ord = b.ord
  JOIN unnest(@array_c::varchar[]) WITH ORDINALITY AS c(val, ord) ON o.ord = c.ord
)
SELECT pairs.num,
       pairs.id,
       pairs.description,
FROM pairs
```
