### ISSUE TITLE
Add comments for individual enum names

### ISSUE THREAD

**Issue by kevinburke1** [sqlc-dev/sqlc#966]
In particular since enums represent things like statuses, it's useful to be able to leave a description for each field of the enum so people can figure out what it does. 

Unfortunately the COMMENT ON functionality only allows a comment on the type, not the individual fields...

**Comment by kyleconroy** [comment]
Any suggestion for the syntax? The only thing I could think of is comments on a per-value basis, which isn't great.

```
CREATE TYPE mood AS ENUM (
  'sad', -- sad value
  'ok', -- okay value
  'happy' -- a very happy user
);
```

**Comment by kevinburkemeter** [comment]
Yeah oh gosh or other option, just a map in sqlc.yaml of constant name =>
code comment.

**Comment by imraan-go** [comment]
> Any suggestion for the syntax? The only thing I could think of is comments on a per-value basis, which isn't great.
> 
> ```
> CREATE TYPE mood AS ENUM (
>   'sad', -- sad value
>   'ok', -- okay value
>   'happy' -- a very happy user
> );
> ```

This looks like a pretty good solution.
