### ISSUE TITLE
Handle user defined types

### ISSUE THREAD

**Issue by ludusrusso** [sqlc-dev/sqlc#986]
I'd like to use sqlc with user defined types in Postgres.

For instance, if I provide a schema like this:

```sql
CREATE TYPE FOO as (
  foo text
);

CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text,
  foo FOO
);
```

I'd expect an output model like that

```golang
type Foo struct {
  foo sql.NullString
}

type Author struct {
   ID   int64
   Name string
   Bio  sql.NullString
   Foo  *Foo
}​
```

Do you think this is feasible?

If for you this is ok I can try to do a PR on it!

**Comment by kyleconroy** [comment]
@ludusrusso No current plans to support user defined types. I'd love to, but there's a lot of other lower hanging fruit that needs to be worked on first.

**Comment by kyleconroy** [comment]
Tracking via https://github.com/sqlc-dev/sqlc/issues/2760
